/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.CauHinhThuTienTruoc;
import com.mb.model.CauHinhThuTienTruocModel;
import com.mb.model.CauHinhThuTienTruocSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CauHinhThuTienTruoc service. Represents a row in the &quot;dm_cauhinhthutientruoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CauHinhThuTienTruocModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CauHinhThuTienTruocImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CauHinhThuTienTruocImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CauHinhThuTienTruocModelImpl
	extends BaseModelImpl<CauHinhThuTienTruoc>
	implements CauHinhThuTienTruocModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cau hinh thu tien truoc model instance should use the <code>CauHinhThuTienTruoc</code> interface instead.
	 */
	public static final String TABLE_NAME = "dm_cauhinhthutientruoc";

	public static final Object[][] TABLE_COLUMNS = {
		{"cauHinhThuTienTruocId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"nam", Types.INTEGER},
		{"ngayTu", Types.TIMESTAMP}, {"ngayDen", Types.TIMESTAMP},
		{"hoatDong", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("cauHinhThuTienTruocId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nam", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ngayTu", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ngayDen", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hoatDong", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dm_cauhinhthutientruoc (cauHinhThuTienTruocId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nam INTEGER,ngayTu DATE null,ngayDen DATE null,hoatDong BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table dm_cauhinhthutientruoc";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cauHinhThuTienTruoc.nam DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dm_cauhinhthutientruoc.nam DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.CauHinhThuTienTruoc"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.CauHinhThuTienTruoc"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.CauHinhThuTienTruoc"),
		true);

	public static final long HOATDONG_COLUMN_BITMASK = 1L;

	public static final long NAM_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CauHinhThuTienTruoc toModel(
		CauHinhThuTienTruocSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		CauHinhThuTienTruoc model = new CauHinhThuTienTruocImpl();

		model.setCauHinhThuTienTruocId(soapModel.getCauHinhThuTienTruocId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setNam(soapModel.getNam());
		model.setNgayTu(soapModel.getNgayTu());
		model.setNgayDen(soapModel.getNgayDen());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CauHinhThuTienTruoc> toModels(
		CauHinhThuTienTruocSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CauHinhThuTienTruoc> models = new ArrayList<CauHinhThuTienTruoc>(
			soapModels.length);

		for (CauHinhThuTienTruocSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.CauHinhThuTienTruoc"));

	public CauHinhThuTienTruocModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cauHinhThuTienTruocId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCauHinhThuTienTruocId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cauHinhThuTienTruocId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CauHinhThuTienTruoc.class;
	}

	@Override
	public String getModelClassName() {
		return CauHinhThuTienTruoc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CauHinhThuTienTruoc, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CauHinhThuTienTruoc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CauHinhThuTienTruoc, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CauHinhThuTienTruoc)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CauHinhThuTienTruoc, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CauHinhThuTienTruoc, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CauHinhThuTienTruoc)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CauHinhThuTienTruoc, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CauHinhThuTienTruoc, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CauHinhThuTienTruoc, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CauHinhThuTienTruoc, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CauHinhThuTienTruoc, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CauHinhThuTienTruoc, Object>>();
		Map<String, BiConsumer<CauHinhThuTienTruoc, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CauHinhThuTienTruoc, ?>>();

		attributeGetterFunctions.put(
			"cauHinhThuTienTruocId",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getCauHinhThuTienTruocId();
				}

			});
		attributeSetterBiConsumers.put(
			"cauHinhThuTienTruocId",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc,
					Object cauHinhThuTienTruocId) {

					cauHinhThuTienTruoc.setCauHinhThuTienTruocId(
						(Long)cauHinhThuTienTruocId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object companyId) {

					cauHinhThuTienTruoc.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object groupId) {

					cauHinhThuTienTruoc.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object userId) {

					cauHinhThuTienTruoc.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object userName) {

					cauHinhThuTienTruoc.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc,
					Object createDate) {

					cauHinhThuTienTruoc.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc,
					Object modifiedDate) {

					cauHinhThuTienTruoc.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"nam",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getNam();
				}

			});
		attributeSetterBiConsumers.put(
			"nam",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object nam) {

					cauHinhThuTienTruoc.setNam((Integer)nam);
				}

			});
		attributeGetterFunctions.put(
			"ngayTu",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getNgayTu();
				}

			});
		attributeSetterBiConsumers.put(
			"ngayTu",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object ngayTu) {

					cauHinhThuTienTruoc.setNgayTu((Date)ngayTu);
				}

			});
		attributeGetterFunctions.put(
			"ngayDen",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getNgayDen();
				}

			});
		attributeSetterBiConsumers.put(
			"ngayDen",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object ngayDen) {

					cauHinhThuTienTruoc.setNgayDen((Date)ngayDen);
				}

			});
		attributeGetterFunctions.put(
			"hoatDong",
			new Function<CauHinhThuTienTruoc, Object>() {

				@Override
				public Object apply(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
					return cauHinhThuTienTruoc.getHoatDong();
				}

			});
		attributeSetterBiConsumers.put(
			"hoatDong",
			new BiConsumer<CauHinhThuTienTruoc, Object>() {

				@Override
				public void accept(
					CauHinhThuTienTruoc cauHinhThuTienTruoc, Object hoatDong) {

					cauHinhThuTienTruoc.setHoatDong((Boolean)hoatDong);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCauHinhThuTienTruocId() {
		return _cauHinhThuTienTruocId;
	}

	@Override
	public void setCauHinhThuTienTruocId(long cauHinhThuTienTruocId) {
		_cauHinhThuTienTruocId = cauHinhThuTienTruocId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getNam() {
		return _nam;
	}

	@Override
	public void setNam(int nam) {
		_columnBitmask = -1L;

		if (!_setOriginalNam) {
			_setOriginalNam = true;

			_originalNam = _nam;
		}

		_nam = nam;
	}

	public int getOriginalNam() {
		return _originalNam;
	}

	@JSON
	@Override
	public Date getNgayTu() {
		return _ngayTu;
	}

	@Override
	public void setNgayTu(Date ngayTu) {
		_ngayTu = ngayTu;
	}

	@JSON
	@Override
	public Date getNgayDen() {
		return _ngayDen;
	}

	@Override
	public void setNgayDen(Date ngayDen) {
		_ngayDen = ngayDen;
	}

	@JSON
	@Override
	public Boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(Boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public Boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CauHinhThuTienTruoc.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CauHinhThuTienTruoc toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CauHinhThuTienTruoc)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CauHinhThuTienTruocImpl cauHinhThuTienTruocImpl =
			new CauHinhThuTienTruocImpl();

		cauHinhThuTienTruocImpl.setCauHinhThuTienTruocId(
			getCauHinhThuTienTruocId());
		cauHinhThuTienTruocImpl.setCompanyId(getCompanyId());
		cauHinhThuTienTruocImpl.setGroupId(getGroupId());
		cauHinhThuTienTruocImpl.setUserId(getUserId());
		cauHinhThuTienTruocImpl.setUserName(getUserName());
		cauHinhThuTienTruocImpl.setCreateDate(getCreateDate());
		cauHinhThuTienTruocImpl.setModifiedDate(getModifiedDate());
		cauHinhThuTienTruocImpl.setNam(getNam());
		cauHinhThuTienTruocImpl.setNgayTu(getNgayTu());
		cauHinhThuTienTruocImpl.setNgayDen(getNgayDen());
		cauHinhThuTienTruocImpl.setHoatDong(getHoatDong());

		cauHinhThuTienTruocImpl.resetOriginalValues();

		return cauHinhThuTienTruocImpl;
	}

	@Override
	public int compareTo(CauHinhThuTienTruoc cauHinhThuTienTruoc) {
		int value = 0;

		if (getNam() < cauHinhThuTienTruoc.getNam()) {
			value = -1;
		}
		else if (getNam() > cauHinhThuTienTruoc.getNam()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CauHinhThuTienTruoc)) {
			return false;
		}

		CauHinhThuTienTruoc cauHinhThuTienTruoc = (CauHinhThuTienTruoc)obj;

		long primaryKey = cauHinhThuTienTruoc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CauHinhThuTienTruocModelImpl cauHinhThuTienTruocModelImpl = this;

		cauHinhThuTienTruocModelImpl._setModifiedDate = false;

		cauHinhThuTienTruocModelImpl._originalNam =
			cauHinhThuTienTruocModelImpl._nam;

		cauHinhThuTienTruocModelImpl._setOriginalNam = false;

		cauHinhThuTienTruocModelImpl._originalHoatDong =
			cauHinhThuTienTruocModelImpl._hoatDong;

		cauHinhThuTienTruocModelImpl._setOriginalHoatDong = false;

		cauHinhThuTienTruocModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CauHinhThuTienTruoc> toCacheModel() {
		CauHinhThuTienTruocCacheModel cauHinhThuTienTruocCacheModel =
			new CauHinhThuTienTruocCacheModel();

		cauHinhThuTienTruocCacheModel.cauHinhThuTienTruocId =
			getCauHinhThuTienTruocId();

		cauHinhThuTienTruocCacheModel.companyId = getCompanyId();

		cauHinhThuTienTruocCacheModel.groupId = getGroupId();

		cauHinhThuTienTruocCacheModel.userId = getUserId();

		cauHinhThuTienTruocCacheModel.userName = getUserName();

		String userName = cauHinhThuTienTruocCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cauHinhThuTienTruocCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cauHinhThuTienTruocCacheModel.createDate = createDate.getTime();
		}
		else {
			cauHinhThuTienTruocCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cauHinhThuTienTruocCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cauHinhThuTienTruocCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cauHinhThuTienTruocCacheModel.nam = getNam();

		Date ngayTu = getNgayTu();

		if (ngayTu != null) {
			cauHinhThuTienTruocCacheModel.ngayTu = ngayTu.getTime();
		}
		else {
			cauHinhThuTienTruocCacheModel.ngayTu = Long.MIN_VALUE;
		}

		Date ngayDen = getNgayDen();

		if (ngayDen != null) {
			cauHinhThuTienTruocCacheModel.ngayDen = ngayDen.getTime();
		}
		else {
			cauHinhThuTienTruocCacheModel.ngayDen = Long.MIN_VALUE;
		}

		cauHinhThuTienTruocCacheModel.hoatDong = getHoatDong();

		return cauHinhThuTienTruocCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CauHinhThuTienTruoc, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CauHinhThuTienTruoc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CauHinhThuTienTruoc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CauHinhThuTienTruoc)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CauHinhThuTienTruoc, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CauHinhThuTienTruoc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CauHinhThuTienTruoc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CauHinhThuTienTruoc)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		CauHinhThuTienTruoc.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		CauHinhThuTienTruoc.class, ModelWrapper.class
	};

	private long _cauHinhThuTienTruocId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _nam;
	private int _originalNam;
	private boolean _setOriginalNam;
	private Date _ngayTu;
	private Date _ngayDen;
	private Boolean _hoatDong;
	private Boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private long _columnBitmask;
	private CauHinhThuTienTruoc _escapedModel;

}