/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.ChiNhanh;
import com.mb.model.ChiNhanhModel;
import com.mb.model.ChiNhanhSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ChiNhanh service. Represents a row in the &quot;dm_chinhanh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ChiNhanhModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChiNhanhImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChiNhanhImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ChiNhanhModelImpl
	extends BaseModelImpl<ChiNhanh> implements ChiNhanhModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chi nhanh model instance should use the <code>ChiNhanh</code> interface instead.
	 */
	public static final String TABLE_NAME = "dm_chinhanh";

	public static final Object[][] TABLE_COLUMNS = {
		{"chiNhanhId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"ma", Types.VARCHAR},
		{"ten", Types.VARCHAR}, {"hoatDong", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("chiNhanhId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ma", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hoatDong", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dm_chinhanh (chiNhanhId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ma VARCHAR(75) null,ten VARCHAR(75) null,hoatDong BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table dm_chinhanh";

	public static final String ORDER_BY_JPQL =
		" ORDER BY chiNhanh.chiNhanhId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dm_chinhanh.chiNhanhId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.ChiNhanh"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.ChiNhanh"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.ChiNhanh"),
		true);

	public static final long HOATDONG_COLUMN_BITMASK = 1L;

	public static final long MA_COLUMN_BITMASK = 2L;

	public static final long CHINHANHID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ChiNhanh toModel(ChiNhanhSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ChiNhanh model = new ChiNhanhImpl();

		model.setChiNhanhId(soapModel.getChiNhanhId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMa(soapModel.getMa());
		model.setTen(soapModel.getTen());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ChiNhanh> toModels(ChiNhanhSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ChiNhanh> models = new ArrayList<ChiNhanh>(soapModels.length);

		for (ChiNhanhSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.ChiNhanh"));

	public ChiNhanhModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _chiNhanhId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChiNhanhId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _chiNhanhId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChiNhanh.class;
	}

	@Override
	public String getModelClassName() {
		return ChiNhanh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ChiNhanh, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ChiNhanh, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChiNhanh, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ChiNhanh)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ChiNhanh, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ChiNhanh, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ChiNhanh)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ChiNhanh, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ChiNhanh, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ChiNhanh, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ChiNhanh, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ChiNhanh, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ChiNhanh, Object>>();
		Map<String, BiConsumer<ChiNhanh, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ChiNhanh, ?>>();

		attributeGetterFunctions.put(
			"chiNhanhId",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getChiNhanhId();
				}

			});
		attributeSetterBiConsumers.put(
			"chiNhanhId",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object chiNhanhId) {
					chiNhanh.setChiNhanhId((Long)chiNhanhId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object companyId) {
					chiNhanh.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object groupId) {
					chiNhanh.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object userId) {
					chiNhanh.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object userName) {
					chiNhanh.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object createDate) {
					chiNhanh.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object modifiedDate) {
					chiNhanh.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"ma",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getMa();
				}

			});
		attributeSetterBiConsumers.put(
			"ma",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object ma) {
					chiNhanh.setMa((String)ma);
				}

			});
		attributeGetterFunctions.put(
			"ten",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getTen();
				}

			});
		attributeSetterBiConsumers.put(
			"ten",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object ten) {
					chiNhanh.setTen((String)ten);
				}

			});
		attributeGetterFunctions.put(
			"hoatDong",
			new Function<ChiNhanh, Object>() {

				@Override
				public Object apply(ChiNhanh chiNhanh) {
					return chiNhanh.getHoatDong();
				}

			});
		attributeSetterBiConsumers.put(
			"hoatDong",
			new BiConsumer<ChiNhanh, Object>() {

				@Override
				public void accept(ChiNhanh chiNhanh, Object hoatDong) {
					chiNhanh.setHoatDong((Boolean)hoatDong);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getChiNhanhId() {
		return _chiNhanhId;
	}

	@Override
	public void setChiNhanhId(long chiNhanhId) {
		_columnBitmask = -1L;

		_chiNhanhId = chiNhanhId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMa() {
		if (_ma == null) {
			return "";
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_ten = ten;
	}

	@JSON
	@Override
	public Boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(Boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public Boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ChiNhanh.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChiNhanh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ChiNhanh)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChiNhanhImpl chiNhanhImpl = new ChiNhanhImpl();

		chiNhanhImpl.setChiNhanhId(getChiNhanhId());
		chiNhanhImpl.setCompanyId(getCompanyId());
		chiNhanhImpl.setGroupId(getGroupId());
		chiNhanhImpl.setUserId(getUserId());
		chiNhanhImpl.setUserName(getUserName());
		chiNhanhImpl.setCreateDate(getCreateDate());
		chiNhanhImpl.setModifiedDate(getModifiedDate());
		chiNhanhImpl.setMa(getMa());
		chiNhanhImpl.setTen(getTen());
		chiNhanhImpl.setHoatDong(getHoatDong());

		chiNhanhImpl.resetOriginalValues();

		return chiNhanhImpl;
	}

	@Override
	public int compareTo(ChiNhanh chiNhanh) {
		int value = 0;

		if (getChiNhanhId() < chiNhanh.getChiNhanhId()) {
			value = -1;
		}
		else if (getChiNhanhId() > chiNhanh.getChiNhanhId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChiNhanh)) {
			return false;
		}

		ChiNhanh chiNhanh = (ChiNhanh)obj;

		long primaryKey = chiNhanh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ChiNhanhModelImpl chiNhanhModelImpl = this;

		chiNhanhModelImpl._setModifiedDate = false;

		chiNhanhModelImpl._originalMa = chiNhanhModelImpl._ma;

		chiNhanhModelImpl._originalHoatDong = chiNhanhModelImpl._hoatDong;

		chiNhanhModelImpl._setOriginalHoatDong = false;

		chiNhanhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChiNhanh> toCacheModel() {
		ChiNhanhCacheModel chiNhanhCacheModel = new ChiNhanhCacheModel();

		chiNhanhCacheModel.chiNhanhId = getChiNhanhId();

		chiNhanhCacheModel.companyId = getCompanyId();

		chiNhanhCacheModel.groupId = getGroupId();

		chiNhanhCacheModel.userId = getUserId();

		chiNhanhCacheModel.userName = getUserName();

		String userName = chiNhanhCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			chiNhanhCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			chiNhanhCacheModel.createDate = createDate.getTime();
		}
		else {
			chiNhanhCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			chiNhanhCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			chiNhanhCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		chiNhanhCacheModel.ma = getMa();

		String ma = chiNhanhCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			chiNhanhCacheModel.ma = null;
		}

		chiNhanhCacheModel.ten = getTen();

		String ten = chiNhanhCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			chiNhanhCacheModel.ten = null;
		}

		chiNhanhCacheModel.hoatDong = getHoatDong();

		return chiNhanhCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ChiNhanh, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ChiNhanh, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChiNhanh, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ChiNhanh)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ChiNhanh, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ChiNhanh, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChiNhanh, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ChiNhanh)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		ChiNhanh.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		ChiNhanh.class, ModelWrapper.class
	};

	private long _chiNhanhId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ma;
	private String _originalMa;
	private String _ten;
	private Boolean _hoatDong;
	private Boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private long _columnBitmask;
	private ChiNhanh _escapedModel;

}