/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.KhachHang;
import com.mb.model.KhachHangModel;
import com.mb.model.KhachHangSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the KhachHang service. Represents a row in the &quot;dm_khachhang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>KhachHangModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KhachHangImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KhachHangImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class KhachHangModelImpl
	extends BaseModelImpl<KhachHang> implements KhachHangModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a khach hang model instance should use the <code>KhachHang</code> interface instead.
	 */
	public static final String TABLE_NAME = "dm_khachhang";

	public static final Object[][] TABLE_COLUMNS = {
		{"khachHangId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"maCTV", Types.VARCHAR},
		{"ma", Types.VARCHAR}, {"hoTen", Types.VARCHAR},
		{"soCMND", Types.VARCHAR}, {"diaChi", Types.VARCHAR},
		{"hoatDong", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("khachHangId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("maCTV", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ma", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hoTen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("soCMND", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("diaChi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hoatDong", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dm_khachhang (khachHangId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,maCTV VARCHAR(75) null,ma VARCHAR(75) null,hoTen VARCHAR(75) null,soCMND VARCHAR(75) null,diaChi VARCHAR(75) null,hoatDong BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table dm_khachhang";

	public static final String ORDER_BY_JPQL =
		" ORDER BY khachHang.khachHangId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dm_khachhang.khachHangId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.KhachHang"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.KhachHang"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.KhachHang"),
		true);

	public static final long MA_COLUMN_BITMASK = 1L;

	public static final long MACTV_COLUMN_BITMASK = 2L;

	public static final long SOCMND_COLUMN_BITMASK = 4L;

	public static final long KHACHHANGID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static KhachHang toModel(KhachHangSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		KhachHang model = new KhachHangImpl();

		model.setKhachHangId(soapModel.getKhachHangId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMaCTV(soapModel.getMaCTV());
		model.setMa(soapModel.getMa());
		model.setHoTen(soapModel.getHoTen());
		model.setSoCMND(soapModel.getSoCMND());
		model.setDiaChi(soapModel.getDiaChi());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<KhachHang> toModels(KhachHangSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<KhachHang> models = new ArrayList<KhachHang>(soapModels.length);

		for (KhachHangSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.KhachHang"));

	public KhachHangModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _khachHangId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setKhachHangId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _khachHangId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KhachHang.class;
	}

	@Override
	public String getModelClassName() {
		return KhachHang.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<KhachHang, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<KhachHang, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KhachHang, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((KhachHang)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<KhachHang, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<KhachHang, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(KhachHang)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<KhachHang, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<KhachHang, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<KhachHang, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<KhachHang, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<KhachHang, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<KhachHang, Object>>();
		Map<String, BiConsumer<KhachHang, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<KhachHang, ?>>();

		attributeGetterFunctions.put(
			"khachHangId",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getKhachHangId();
				}

			});
		attributeSetterBiConsumers.put(
			"khachHangId",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object khachHangId) {
					khachHang.setKhachHangId((Long)khachHangId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object companyId) {
					khachHang.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object groupId) {
					khachHang.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object userId) {
					khachHang.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object userName) {
					khachHang.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object createDate) {
					khachHang.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object modifiedDate) {
					khachHang.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"maCTV",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getMaCTV();
				}

			});
		attributeSetterBiConsumers.put(
			"maCTV",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object maCTV) {
					khachHang.setMaCTV((String)maCTV);
				}

			});
		attributeGetterFunctions.put(
			"ma",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getMa();
				}

			});
		attributeSetterBiConsumers.put(
			"ma",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object ma) {
					khachHang.setMa((String)ma);
				}

			});
		attributeGetterFunctions.put(
			"hoTen",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getHoTen();
				}

			});
		attributeSetterBiConsumers.put(
			"hoTen",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object hoTen) {
					khachHang.setHoTen((String)hoTen);
				}

			});
		attributeGetterFunctions.put(
			"soCMND",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getSoCMND();
				}

			});
		attributeSetterBiConsumers.put(
			"soCMND",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object soCMND) {
					khachHang.setSoCMND((String)soCMND);
				}

			});
		attributeGetterFunctions.put(
			"diaChi",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getDiaChi();
				}

			});
		attributeSetterBiConsumers.put(
			"diaChi",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object diaChi) {
					khachHang.setDiaChi((String)diaChi);
				}

			});
		attributeGetterFunctions.put(
			"hoatDong",
			new Function<KhachHang, Object>() {

				@Override
				public Object apply(KhachHang khachHang) {
					return khachHang.getHoatDong();
				}

			});
		attributeSetterBiConsumers.put(
			"hoatDong",
			new BiConsumer<KhachHang, Object>() {

				@Override
				public void accept(KhachHang khachHang, Object hoatDong) {
					khachHang.setHoatDong((Boolean)hoatDong);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getKhachHangId() {
		return _khachHangId;
	}

	@Override
	public void setKhachHangId(long khachHangId) {
		_columnBitmask = -1L;

		_khachHangId = khachHangId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMaCTV() {
		if (_maCTV == null) {
			return "";
		}
		else {
			return _maCTV;
		}
	}

	@Override
	public void setMaCTV(String maCTV) {
		_columnBitmask |= MACTV_COLUMN_BITMASK;

		if (_originalMaCTV == null) {
			_originalMaCTV = _maCTV;
		}

		_maCTV = maCTV;
	}

	public String getOriginalMaCTV() {
		return GetterUtil.getString(_originalMaCTV);
	}

	@JSON
	@Override
	public String getMa() {
		if (_ma == null) {
			return "";
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	@JSON
	@Override
	public String getHoTen() {
		if (_hoTen == null) {
			return "";
		}
		else {
			return _hoTen;
		}
	}

	@Override
	public void setHoTen(String hoTen) {
		_hoTen = hoTen;
	}

	@JSON
	@Override
	public String getSoCMND() {
		if (_soCMND == null) {
			return "";
		}
		else {
			return _soCMND;
		}
	}

	@Override
	public void setSoCMND(String soCMND) {
		_columnBitmask |= SOCMND_COLUMN_BITMASK;

		if (_originalSoCMND == null) {
			_originalSoCMND = _soCMND;
		}

		_soCMND = soCMND;
	}

	public String getOriginalSoCMND() {
		return GetterUtil.getString(_originalSoCMND);
	}

	@JSON
	@Override
	public String getDiaChi() {
		if (_diaChi == null) {
			return "";
		}
		else {
			return _diaChi;
		}
	}

	@Override
	public void setDiaChi(String diaChi) {
		_diaChi = diaChi;
	}

	@JSON
	@Override
	public Boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(Boolean hoatDong) {
		_hoatDong = hoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), KhachHang.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KhachHang toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (KhachHang)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KhachHangImpl khachHangImpl = new KhachHangImpl();

		khachHangImpl.setKhachHangId(getKhachHangId());
		khachHangImpl.setCompanyId(getCompanyId());
		khachHangImpl.setGroupId(getGroupId());
		khachHangImpl.setUserId(getUserId());
		khachHangImpl.setUserName(getUserName());
		khachHangImpl.setCreateDate(getCreateDate());
		khachHangImpl.setModifiedDate(getModifiedDate());
		khachHangImpl.setMaCTV(getMaCTV());
		khachHangImpl.setMa(getMa());
		khachHangImpl.setHoTen(getHoTen());
		khachHangImpl.setSoCMND(getSoCMND());
		khachHangImpl.setDiaChi(getDiaChi());
		khachHangImpl.setHoatDong(getHoatDong());

		khachHangImpl.resetOriginalValues();

		return khachHangImpl;
	}

	@Override
	public int compareTo(KhachHang khachHang) {
		int value = 0;

		if (getKhachHangId() < khachHang.getKhachHangId()) {
			value = -1;
		}
		else if (getKhachHangId() > khachHang.getKhachHangId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof KhachHang)) {
			return false;
		}

		KhachHang khachHang = (KhachHang)obj;

		long primaryKey = khachHang.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		KhachHangModelImpl khachHangModelImpl = this;

		khachHangModelImpl._setModifiedDate = false;

		khachHangModelImpl._originalMaCTV = khachHangModelImpl._maCTV;

		khachHangModelImpl._originalMa = khachHangModelImpl._ma;

		khachHangModelImpl._originalSoCMND = khachHangModelImpl._soCMND;

		khachHangModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<KhachHang> toCacheModel() {
		KhachHangCacheModel khachHangCacheModel = new KhachHangCacheModel();

		khachHangCacheModel.khachHangId = getKhachHangId();

		khachHangCacheModel.companyId = getCompanyId();

		khachHangCacheModel.groupId = getGroupId();

		khachHangCacheModel.userId = getUserId();

		khachHangCacheModel.userName = getUserName();

		String userName = khachHangCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			khachHangCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			khachHangCacheModel.createDate = createDate.getTime();
		}
		else {
			khachHangCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			khachHangCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			khachHangCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		khachHangCacheModel.maCTV = getMaCTV();

		String maCTV = khachHangCacheModel.maCTV;

		if ((maCTV != null) && (maCTV.length() == 0)) {
			khachHangCacheModel.maCTV = null;
		}

		khachHangCacheModel.ma = getMa();

		String ma = khachHangCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			khachHangCacheModel.ma = null;
		}

		khachHangCacheModel.hoTen = getHoTen();

		String hoTen = khachHangCacheModel.hoTen;

		if ((hoTen != null) && (hoTen.length() == 0)) {
			khachHangCacheModel.hoTen = null;
		}

		khachHangCacheModel.soCMND = getSoCMND();

		String soCMND = khachHangCacheModel.soCMND;

		if ((soCMND != null) && (soCMND.length() == 0)) {
			khachHangCacheModel.soCMND = null;
		}

		khachHangCacheModel.diaChi = getDiaChi();

		String diaChi = khachHangCacheModel.diaChi;

		if ((diaChi != null) && (diaChi.length() == 0)) {
			khachHangCacheModel.diaChi = null;
		}

		khachHangCacheModel.hoatDong = getHoatDong();

		return khachHangCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<KhachHang, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<KhachHang, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KhachHang, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((KhachHang)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<KhachHang, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<KhachHang, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KhachHang, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((KhachHang)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		KhachHang.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		KhachHang.class, ModelWrapper.class
	};

	private long _khachHangId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _maCTV;
	private String _originalMaCTV;
	private String _ma;
	private String _originalMa;
	private String _hoTen;
	private String _soCMND;
	private String _originalSoCMND;
	private String _diaChi;
	private Boolean _hoatDong;
	private long _columnBitmask;
	private KhachHang _escapedModel;

}