/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.LoaiTaiSan;
import com.mb.model.LoaiTaiSanModel;
import com.mb.model.LoaiTaiSanSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LoaiTaiSan service. Represents a row in the &quot;dm_loaiTaiSan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LoaiTaiSanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoaiTaiSanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoaiTaiSanImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LoaiTaiSanModelImpl
	extends BaseModelImpl<LoaiTaiSan> implements LoaiTaiSanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loai tai san model instance should use the <code>LoaiTaiSan</code> interface instead.
	 */
	public static final String TABLE_NAME = "dm_loaiTaiSan";

	public static final Object[][] TABLE_COLUMNS = {
		{"loaiTaiSanId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"ten", Types.VARCHAR},
		{"ma", Types.VARCHAR}, {"ghiChu", Types.VARCHAR},
		{"hoatDong", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("loaiTaiSanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ma", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ghiChu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hoatDong", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dm_loaiTaiSan (loaiTaiSanId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ten VARCHAR(75) null,ma VARCHAR(75) null,ghiChu VARCHAR(75) null,hoatDong BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table dm_loaiTaiSan";

	public static final String ORDER_BY_JPQL =
		" ORDER BY loaiTaiSan.loaiTaiSanId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dm_loaiTaiSan.loaiTaiSanId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.LoaiTaiSan"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.LoaiTaiSan"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.LoaiTaiSan"),
		true);

	public static final long MA_COLUMN_BITMASK = 1L;

	public static final long LOAITAISANID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LoaiTaiSan toModel(LoaiTaiSanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LoaiTaiSan model = new LoaiTaiSanImpl();

		model.setLoaiTaiSanId(soapModel.getLoaiTaiSanId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTen(soapModel.getTen());
		model.setMa(soapModel.getMa());
		model.setGhiChu(soapModel.getGhiChu());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LoaiTaiSan> toModels(LoaiTaiSanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LoaiTaiSan> models = new ArrayList<LoaiTaiSan>(soapModels.length);

		for (LoaiTaiSanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.LoaiTaiSan"));

	public LoaiTaiSanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loaiTaiSanId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoaiTaiSanId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loaiTaiSanId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoaiTaiSan.class;
	}

	@Override
	public String getModelClassName() {
		return LoaiTaiSan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LoaiTaiSan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LoaiTaiSan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoaiTaiSan, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LoaiTaiSan)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LoaiTaiSan, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LoaiTaiSan, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LoaiTaiSan)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LoaiTaiSan, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LoaiTaiSan, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LoaiTaiSan, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LoaiTaiSan, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LoaiTaiSan, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LoaiTaiSan, Object>>();
		Map<String, BiConsumer<LoaiTaiSan, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LoaiTaiSan, ?>>();

		attributeGetterFunctions.put(
			"loaiTaiSanId",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getLoaiTaiSanId();
				}

			});
		attributeSetterBiConsumers.put(
			"loaiTaiSanId",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object loaiTaiSanId) {
					loaiTaiSan.setLoaiTaiSanId((Long)loaiTaiSanId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object companyId) {
					loaiTaiSan.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object groupId) {
					loaiTaiSan.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object userId) {
					loaiTaiSan.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object userName) {
					loaiTaiSan.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object createDate) {
					loaiTaiSan.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object modifiedDate) {
					loaiTaiSan.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"ten",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getTen();
				}

			});
		attributeSetterBiConsumers.put(
			"ten",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object ten) {
					loaiTaiSan.setTen((String)ten);
				}

			});
		attributeGetterFunctions.put(
			"ma",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getMa();
				}

			});
		attributeSetterBiConsumers.put(
			"ma",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object ma) {
					loaiTaiSan.setMa((String)ma);
				}

			});
		attributeGetterFunctions.put(
			"ghiChu",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getGhiChu();
				}

			});
		attributeSetterBiConsumers.put(
			"ghiChu",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object ghiChu) {
					loaiTaiSan.setGhiChu((String)ghiChu);
				}

			});
		attributeGetterFunctions.put(
			"hoatDong",
			new Function<LoaiTaiSan, Object>() {

				@Override
				public Object apply(LoaiTaiSan loaiTaiSan) {
					return loaiTaiSan.getHoatDong();
				}

			});
		attributeSetterBiConsumers.put(
			"hoatDong",
			new BiConsumer<LoaiTaiSan, Object>() {

				@Override
				public void accept(LoaiTaiSan loaiTaiSan, Object hoatDong) {
					loaiTaiSan.setHoatDong((Boolean)hoatDong);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getLoaiTaiSanId() {
		return _loaiTaiSanId;
	}

	@Override
	public void setLoaiTaiSanId(long loaiTaiSanId) {
		_columnBitmask = -1L;

		_loaiTaiSanId = loaiTaiSanId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_ten = ten;
	}

	@JSON
	@Override
	public String getMa() {
		if (_ma == null) {
			return "";
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return "";
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@JSON
	@Override
	public Boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(Boolean hoatDong) {
		_hoatDong = hoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LoaiTaiSan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoaiTaiSan toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LoaiTaiSan)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoaiTaiSanImpl loaiTaiSanImpl = new LoaiTaiSanImpl();

		loaiTaiSanImpl.setLoaiTaiSanId(getLoaiTaiSanId());
		loaiTaiSanImpl.setCompanyId(getCompanyId());
		loaiTaiSanImpl.setGroupId(getGroupId());
		loaiTaiSanImpl.setUserId(getUserId());
		loaiTaiSanImpl.setUserName(getUserName());
		loaiTaiSanImpl.setCreateDate(getCreateDate());
		loaiTaiSanImpl.setModifiedDate(getModifiedDate());
		loaiTaiSanImpl.setTen(getTen());
		loaiTaiSanImpl.setMa(getMa());
		loaiTaiSanImpl.setGhiChu(getGhiChu());
		loaiTaiSanImpl.setHoatDong(getHoatDong());

		loaiTaiSanImpl.resetOriginalValues();

		return loaiTaiSanImpl;
	}

	@Override
	public int compareTo(LoaiTaiSan loaiTaiSan) {
		int value = 0;

		if (getLoaiTaiSanId() < loaiTaiSan.getLoaiTaiSanId()) {
			value = -1;
		}
		else if (getLoaiTaiSanId() > loaiTaiSan.getLoaiTaiSanId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoaiTaiSan)) {
			return false;
		}

		LoaiTaiSan loaiTaiSan = (LoaiTaiSan)obj;

		long primaryKey = loaiTaiSan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LoaiTaiSanModelImpl loaiTaiSanModelImpl = this;

		loaiTaiSanModelImpl._setModifiedDate = false;

		loaiTaiSanModelImpl._originalMa = loaiTaiSanModelImpl._ma;

		loaiTaiSanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LoaiTaiSan> toCacheModel() {
		LoaiTaiSanCacheModel loaiTaiSanCacheModel = new LoaiTaiSanCacheModel();

		loaiTaiSanCacheModel.loaiTaiSanId = getLoaiTaiSanId();

		loaiTaiSanCacheModel.companyId = getCompanyId();

		loaiTaiSanCacheModel.groupId = getGroupId();

		loaiTaiSanCacheModel.userId = getUserId();

		loaiTaiSanCacheModel.userName = getUserName();

		String userName = loaiTaiSanCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loaiTaiSanCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			loaiTaiSanCacheModel.createDate = createDate.getTime();
		}
		else {
			loaiTaiSanCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			loaiTaiSanCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			loaiTaiSanCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		loaiTaiSanCacheModel.ten = getTen();

		String ten = loaiTaiSanCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			loaiTaiSanCacheModel.ten = null;
		}

		loaiTaiSanCacheModel.ma = getMa();

		String ma = loaiTaiSanCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			loaiTaiSanCacheModel.ma = null;
		}

		loaiTaiSanCacheModel.ghiChu = getGhiChu();

		String ghiChu = loaiTaiSanCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			loaiTaiSanCacheModel.ghiChu = null;
		}

		loaiTaiSanCacheModel.hoatDong = getHoatDong();

		return loaiTaiSanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LoaiTaiSan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LoaiTaiSan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoaiTaiSan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LoaiTaiSan)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LoaiTaiSan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LoaiTaiSan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoaiTaiSan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LoaiTaiSan)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		LoaiTaiSan.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		LoaiTaiSan.class, ModelWrapper.class
	};

	private long _loaiTaiSanId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ten;
	private String _ma;
	private String _originalMa;
	private String _ghiChu;
	private Boolean _hoatDong;
	private long _columnBitmask;
	private LoaiTaiSan _escapedModel;

}