/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.mb.model.LoaiTaiSan;
import com.mb.service.LoaiTaiSanLocalServiceUtil;

/**
 * The extended model base implementation for the LoaiTaiSan service. Represents a row in the &quot;dm_loaiTaiSan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoaiTaiSanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoaiTaiSanImpl
 * @see LoaiTaiSan
 * @generated
 */
@ProviderType
public abstract class LoaiTaiSanBaseImpl
	extends LoaiTaiSanModelImpl implements LoaiTaiSan {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loai tai san model instance should use the <code>LoaiTaiSan</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LoaiTaiSanLocalServiceUtil.addLoaiTaiSan(this);
		}
		else {
			LoaiTaiSanLocalServiceUtil.updateLoaiTaiSan(this);
		}
	}

}