/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.MaSoThuChi;
import com.mb.model.MaSoThuChiModel;
import com.mb.model.MaSoThuChiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MaSoThuChi service. Represents a row in the &quot;dm_masothuchi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>MaSoThuChiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MaSoThuChiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MaSoThuChiImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MaSoThuChiModelImpl
	extends BaseModelImpl<MaSoThuChi> implements MaSoThuChiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ma so thu chi model instance should use the <code>MaSoThuChi</code> interface instead.
	 */
	public static final String TABLE_NAME = "dm_masothuchi";

	public static final Object[][] TABLE_COLUMNS = {
		{"maSoThuChiId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"ma", Types.VARCHAR},
		{"dienGiai", Types.VARCHAR}, {"loai", Types.INTEGER},
		{"hoatDong", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("maSoThuChiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ma", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dienGiai", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loai", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("hoatDong", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dm_masothuchi (maSoThuChiId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ma VARCHAR(75) null,dienGiai VARCHAR(75) null,loai INTEGER,hoatDong BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table dm_masothuchi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY maSoThuChi.maSoThuChiId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dm_masothuchi.maSoThuChiId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.MaSoThuChi"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.MaSoThuChi"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.MaSoThuChi"),
		true);

	public static final long HOATDONG_COLUMN_BITMASK = 1L;

	public static final long LOAI_COLUMN_BITMASK = 2L;

	public static final long MA_COLUMN_BITMASK = 4L;

	public static final long MASOTHUCHIID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MaSoThuChi toModel(MaSoThuChiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MaSoThuChi model = new MaSoThuChiImpl();

		model.setMaSoThuChiId(soapModel.getMaSoThuChiId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMa(soapModel.getMa());
		model.setDienGiai(soapModel.getDienGiai());
		model.setLoai(soapModel.getLoai());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MaSoThuChi> toModels(MaSoThuChiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MaSoThuChi> models = new ArrayList<MaSoThuChi>(soapModels.length);

		for (MaSoThuChiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.MaSoThuChi"));

	public MaSoThuChiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _maSoThuChiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMaSoThuChiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _maSoThuChiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MaSoThuChi.class;
	}

	@Override
	public String getModelClassName() {
		return MaSoThuChi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MaSoThuChi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MaSoThuChi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MaSoThuChi, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MaSoThuChi)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MaSoThuChi, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MaSoThuChi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MaSoThuChi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MaSoThuChi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MaSoThuChi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MaSoThuChi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MaSoThuChi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MaSoThuChi, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MaSoThuChi, Object>>();
		Map<String, BiConsumer<MaSoThuChi, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MaSoThuChi, ?>>();

		attributeGetterFunctions.put(
			"maSoThuChiId",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getMaSoThuChiId();
				}

			});
		attributeSetterBiConsumers.put(
			"maSoThuChiId",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object maSoThuChiId) {
					maSoThuChi.setMaSoThuChiId((Long)maSoThuChiId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object companyId) {
					maSoThuChi.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object groupId) {
					maSoThuChi.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object userId) {
					maSoThuChi.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object userName) {
					maSoThuChi.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object createDate) {
					maSoThuChi.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object modifiedDate) {
					maSoThuChi.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"ma",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getMa();
				}

			});
		attributeSetterBiConsumers.put(
			"ma",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object ma) {
					maSoThuChi.setMa((String)ma);
				}

			});
		attributeGetterFunctions.put(
			"dienGiai",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getDienGiai();
				}

			});
		attributeSetterBiConsumers.put(
			"dienGiai",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object dienGiai) {
					maSoThuChi.setDienGiai((String)dienGiai);
				}

			});
		attributeGetterFunctions.put(
			"loai",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getLoai();
				}

			});
		attributeSetterBiConsumers.put(
			"loai",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object loai) {
					maSoThuChi.setLoai((Integer)loai);
				}

			});
		attributeGetterFunctions.put(
			"hoatDong",
			new Function<MaSoThuChi, Object>() {

				@Override
				public Object apply(MaSoThuChi maSoThuChi) {
					return maSoThuChi.getHoatDong();
				}

			});
		attributeSetterBiConsumers.put(
			"hoatDong",
			new BiConsumer<MaSoThuChi, Object>() {

				@Override
				public void accept(MaSoThuChi maSoThuChi, Object hoatDong) {
					maSoThuChi.setHoatDong((Boolean)hoatDong);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMaSoThuChiId() {
		return _maSoThuChiId;
	}

	@Override
	public void setMaSoThuChiId(long maSoThuChiId) {
		_columnBitmask = -1L;

		_maSoThuChiId = maSoThuChiId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMa() {
		if (_ma == null) {
			return "";
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	@JSON
	@Override
	public String getDienGiai() {
		if (_dienGiai == null) {
			return "";
		}
		else {
			return _dienGiai;
		}
	}

	@Override
	public void setDienGiai(String dienGiai) {
		_dienGiai = dienGiai;
	}

	@JSON
	@Override
	public int getLoai() {
		return _loai;
	}

	@Override
	public void setLoai(int loai) {
		_columnBitmask |= LOAI_COLUMN_BITMASK;

		if (!_setOriginalLoai) {
			_setOriginalLoai = true;

			_originalLoai = _loai;
		}

		_loai = loai;
	}

	public int getOriginalLoai() {
		return _originalLoai;
	}

	@JSON
	@Override
	public Boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(Boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public Boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MaSoThuChi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MaSoThuChi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MaSoThuChi)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MaSoThuChiImpl maSoThuChiImpl = new MaSoThuChiImpl();

		maSoThuChiImpl.setMaSoThuChiId(getMaSoThuChiId());
		maSoThuChiImpl.setCompanyId(getCompanyId());
		maSoThuChiImpl.setGroupId(getGroupId());
		maSoThuChiImpl.setUserId(getUserId());
		maSoThuChiImpl.setUserName(getUserName());
		maSoThuChiImpl.setCreateDate(getCreateDate());
		maSoThuChiImpl.setModifiedDate(getModifiedDate());
		maSoThuChiImpl.setMa(getMa());
		maSoThuChiImpl.setDienGiai(getDienGiai());
		maSoThuChiImpl.setLoai(getLoai());
		maSoThuChiImpl.setHoatDong(getHoatDong());

		maSoThuChiImpl.resetOriginalValues();

		return maSoThuChiImpl;
	}

	@Override
	public int compareTo(MaSoThuChi maSoThuChi) {
		int value = 0;

		if (getMaSoThuChiId() < maSoThuChi.getMaSoThuChiId()) {
			value = -1;
		}
		else if (getMaSoThuChiId() > maSoThuChi.getMaSoThuChiId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MaSoThuChi)) {
			return false;
		}

		MaSoThuChi maSoThuChi = (MaSoThuChi)obj;

		long primaryKey = maSoThuChi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MaSoThuChiModelImpl maSoThuChiModelImpl = this;

		maSoThuChiModelImpl._setModifiedDate = false;

		maSoThuChiModelImpl._originalMa = maSoThuChiModelImpl._ma;

		maSoThuChiModelImpl._originalLoai = maSoThuChiModelImpl._loai;

		maSoThuChiModelImpl._setOriginalLoai = false;

		maSoThuChiModelImpl._originalHoatDong = maSoThuChiModelImpl._hoatDong;

		maSoThuChiModelImpl._setOriginalHoatDong = false;

		maSoThuChiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MaSoThuChi> toCacheModel() {
		MaSoThuChiCacheModel maSoThuChiCacheModel = new MaSoThuChiCacheModel();

		maSoThuChiCacheModel.maSoThuChiId = getMaSoThuChiId();

		maSoThuChiCacheModel.companyId = getCompanyId();

		maSoThuChiCacheModel.groupId = getGroupId();

		maSoThuChiCacheModel.userId = getUserId();

		maSoThuChiCacheModel.userName = getUserName();

		String userName = maSoThuChiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			maSoThuChiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			maSoThuChiCacheModel.createDate = createDate.getTime();
		}
		else {
			maSoThuChiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			maSoThuChiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			maSoThuChiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		maSoThuChiCacheModel.ma = getMa();

		String ma = maSoThuChiCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			maSoThuChiCacheModel.ma = null;
		}

		maSoThuChiCacheModel.dienGiai = getDienGiai();

		String dienGiai = maSoThuChiCacheModel.dienGiai;

		if ((dienGiai != null) && (dienGiai.length() == 0)) {
			maSoThuChiCacheModel.dienGiai = null;
		}

		maSoThuChiCacheModel.loai = getLoai();

		maSoThuChiCacheModel.hoatDong = getHoatDong();

		return maSoThuChiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MaSoThuChi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MaSoThuChi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MaSoThuChi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((MaSoThuChi)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MaSoThuChi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MaSoThuChi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MaSoThuChi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MaSoThuChi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		MaSoThuChi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		MaSoThuChi.class, ModelWrapper.class
	};

	private long _maSoThuChiId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ma;
	private String _originalMa;
	private String _dienGiai;
	private int _loai;
	private int _originalLoai;
	private boolean _setOriginalLoai;
	private Boolean _hoatDong;
	private Boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private long _columnBitmask;
	private MaSoThuChi _escapedModel;

}