/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.MaSoTheoDoi;
import com.mb.model.MaSoTheoDoiModel;
import com.mb.model.MaSoTheoDoiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MaSoTheoDoi service. Represents a row in the &quot;dm_masotheodoi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>MaSoTheoDoiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MaSoTheoDoiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MaSoTheoDoiImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MaSoTheoDoiModelImpl
	extends BaseModelImpl<MaSoTheoDoi> implements MaSoTheoDoiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ma so theo doi model instance should use the <code>MaSoTheoDoi</code> interface instead.
	 */
	public static final String TABLE_NAME = "dm_masotheodoi";

	public static final Object[][] TABLE_COLUMNS = {
		{"maSoTheoDoiId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"ma", Types.VARCHAR},
		{"dienGiai", Types.VARCHAR}, {"hoatDong", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("maSoTheoDoiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ma", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dienGiai", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hoatDong", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dm_masotheodoi (maSoTheoDoiId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,ma VARCHAR(75) null,dienGiai VARCHAR(75) null,hoatDong BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table dm_masotheodoi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY maSoTheoDoi.maSoTheoDoiId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dm_masotheodoi.maSoTheoDoiId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.MaSoTheoDoi"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.MaSoTheoDoi"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.MaSoTheoDoi"),
		true);

	public static final long MA_COLUMN_BITMASK = 1L;

	public static final long MASOTHEODOIID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MaSoTheoDoi toModel(MaSoTheoDoiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MaSoTheoDoi model = new MaSoTheoDoiImpl();

		model.setMaSoTheoDoiId(soapModel.getMaSoTheoDoiId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMa(soapModel.getMa());
		model.setDienGiai(soapModel.getDienGiai());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MaSoTheoDoi> toModels(MaSoTheoDoiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MaSoTheoDoi> models = new ArrayList<MaSoTheoDoi>(
			soapModels.length);

		for (MaSoTheoDoiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.MaSoTheoDoi"));

	public MaSoTheoDoiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _maSoTheoDoiId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMaSoTheoDoiId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _maSoTheoDoiId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MaSoTheoDoi.class;
	}

	@Override
	public String getModelClassName() {
		return MaSoTheoDoi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MaSoTheoDoi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MaSoTheoDoi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MaSoTheoDoi, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MaSoTheoDoi)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MaSoTheoDoi, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MaSoTheoDoi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MaSoTheoDoi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MaSoTheoDoi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MaSoTheoDoi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MaSoTheoDoi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MaSoTheoDoi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MaSoTheoDoi, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MaSoTheoDoi, Object>>();
		Map<String, BiConsumer<MaSoTheoDoi, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MaSoTheoDoi, ?>>();

		attributeGetterFunctions.put(
			"maSoTheoDoiId",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getMaSoTheoDoiId();
				}

			});
		attributeSetterBiConsumers.put(
			"maSoTheoDoiId",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(
					MaSoTheoDoi maSoTheoDoi, Object maSoTheoDoiId) {

					maSoTheoDoi.setMaSoTheoDoiId((Long)maSoTheoDoiId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object companyId) {
					maSoTheoDoi.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object groupId) {
					maSoTheoDoi.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object userId) {
					maSoTheoDoi.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object userName) {
					maSoTheoDoi.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object createDate) {
					maSoTheoDoi.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(
					MaSoTheoDoi maSoTheoDoi, Object modifiedDate) {

					maSoTheoDoi.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"ma",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getMa();
				}

			});
		attributeSetterBiConsumers.put(
			"ma",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object ma) {
					maSoTheoDoi.setMa((String)ma);
				}

			});
		attributeGetterFunctions.put(
			"dienGiai",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getDienGiai();
				}

			});
		attributeSetterBiConsumers.put(
			"dienGiai",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object dienGiai) {
					maSoTheoDoi.setDienGiai((String)dienGiai);
				}

			});
		attributeGetterFunctions.put(
			"hoatDong",
			new Function<MaSoTheoDoi, Object>() {

				@Override
				public Object apply(MaSoTheoDoi maSoTheoDoi) {
					return maSoTheoDoi.getHoatDong();
				}

			});
		attributeSetterBiConsumers.put(
			"hoatDong",
			new BiConsumer<MaSoTheoDoi, Object>() {

				@Override
				public void accept(MaSoTheoDoi maSoTheoDoi, Object hoatDong) {
					maSoTheoDoi.setHoatDong((Boolean)hoatDong);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMaSoTheoDoiId() {
		return _maSoTheoDoiId;
	}

	@Override
	public void setMaSoTheoDoiId(long maSoTheoDoiId) {
		_columnBitmask = -1L;

		_maSoTheoDoiId = maSoTheoDoiId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMa() {
		if (_ma == null) {
			return "";
		}
		else {
			return _ma;
		}
	}

	@Override
	public void setMa(String ma) {
		_columnBitmask |= MA_COLUMN_BITMASK;

		if (_originalMa == null) {
			_originalMa = _ma;
		}

		_ma = ma;
	}

	public String getOriginalMa() {
		return GetterUtil.getString(_originalMa);
	}

	@JSON
	@Override
	public String getDienGiai() {
		if (_dienGiai == null) {
			return "";
		}
		else {
			return _dienGiai;
		}
	}

	@Override
	public void setDienGiai(String dienGiai) {
		_dienGiai = dienGiai;
	}

	@JSON
	@Override
	public Boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(Boolean hoatDong) {
		_hoatDong = hoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MaSoTheoDoi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MaSoTheoDoi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MaSoTheoDoi)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MaSoTheoDoiImpl maSoTheoDoiImpl = new MaSoTheoDoiImpl();

		maSoTheoDoiImpl.setMaSoTheoDoiId(getMaSoTheoDoiId());
		maSoTheoDoiImpl.setCompanyId(getCompanyId());
		maSoTheoDoiImpl.setGroupId(getGroupId());
		maSoTheoDoiImpl.setUserId(getUserId());
		maSoTheoDoiImpl.setUserName(getUserName());
		maSoTheoDoiImpl.setCreateDate(getCreateDate());
		maSoTheoDoiImpl.setModifiedDate(getModifiedDate());
		maSoTheoDoiImpl.setMa(getMa());
		maSoTheoDoiImpl.setDienGiai(getDienGiai());
		maSoTheoDoiImpl.setHoatDong(getHoatDong());

		maSoTheoDoiImpl.resetOriginalValues();

		return maSoTheoDoiImpl;
	}

	@Override
	public int compareTo(MaSoTheoDoi maSoTheoDoi) {
		int value = 0;

		if (getMaSoTheoDoiId() < maSoTheoDoi.getMaSoTheoDoiId()) {
			value = -1;
		}
		else if (getMaSoTheoDoiId() > maSoTheoDoi.getMaSoTheoDoiId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MaSoTheoDoi)) {
			return false;
		}

		MaSoTheoDoi maSoTheoDoi = (MaSoTheoDoi)obj;

		long primaryKey = maSoTheoDoi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MaSoTheoDoiModelImpl maSoTheoDoiModelImpl = this;

		maSoTheoDoiModelImpl._setModifiedDate = false;

		maSoTheoDoiModelImpl._originalMa = maSoTheoDoiModelImpl._ma;

		maSoTheoDoiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MaSoTheoDoi> toCacheModel() {
		MaSoTheoDoiCacheModel maSoTheoDoiCacheModel =
			new MaSoTheoDoiCacheModel();

		maSoTheoDoiCacheModel.maSoTheoDoiId = getMaSoTheoDoiId();

		maSoTheoDoiCacheModel.companyId = getCompanyId();

		maSoTheoDoiCacheModel.groupId = getGroupId();

		maSoTheoDoiCacheModel.userId = getUserId();

		maSoTheoDoiCacheModel.userName = getUserName();

		String userName = maSoTheoDoiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			maSoTheoDoiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			maSoTheoDoiCacheModel.createDate = createDate.getTime();
		}
		else {
			maSoTheoDoiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			maSoTheoDoiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			maSoTheoDoiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		maSoTheoDoiCacheModel.ma = getMa();

		String ma = maSoTheoDoiCacheModel.ma;

		if ((ma != null) && (ma.length() == 0)) {
			maSoTheoDoiCacheModel.ma = null;
		}

		maSoTheoDoiCacheModel.dienGiai = getDienGiai();

		String dienGiai = maSoTheoDoiCacheModel.dienGiai;

		if ((dienGiai != null) && (dienGiai.length() == 0)) {
			maSoTheoDoiCacheModel.dienGiai = null;
		}

		maSoTheoDoiCacheModel.hoatDong = getHoatDong();

		return maSoTheoDoiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MaSoTheoDoi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MaSoTheoDoi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MaSoTheoDoi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((MaSoTheoDoi)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MaSoTheoDoi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MaSoTheoDoi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MaSoTheoDoi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MaSoTheoDoi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		MaSoTheoDoi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		MaSoTheoDoi.class, ModelWrapper.class
	};

	private long _maSoTheoDoiId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _ma;
	private String _originalMa;
	private String _dienGiai;
	private Boolean _hoatDong;
	private long _columnBitmask;
	private MaSoTheoDoi _escapedModel;

}