/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.TaiKhoanDoiUng;
import com.mb.model.TaiKhoanDoiUngModel;
import com.mb.model.TaiKhoanDoiUngSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TaiKhoanDoiUng service. Represents a row in the &quot;dm_taikhoandoiung&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TaiKhoanDoiUngModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaiKhoanDoiUngImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaiKhoanDoiUngImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TaiKhoanDoiUngModelImpl
	extends BaseModelImpl<TaiKhoanDoiUng> implements TaiKhoanDoiUngModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tai khoan doi ung model instance should use the <code>TaiKhoanDoiUng</code> interface instead.
	 */
	public static final String TABLE_NAME = "dm_taikhoandoiung";

	public static final Object[][] TABLE_COLUMNS = {
		{"taiKhoanDoiUngId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"taiKhoanDoiUngChaId", Types.BIGINT}, {"soHieu", Types.VARCHAR},
		{"ten", Types.VARCHAR}, {"dienGiaiTheoDoi", Types.VARCHAR},
		{"loaiTaiKhoan", Types.INTEGER}, {"hoatDong", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("taiKhoanDoiUngId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("taiKhoanDoiUngChaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("soHieu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dienGiaiTheoDoi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loaiTaiKhoan", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("hoatDong", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table dm_taikhoandoiung (taiKhoanDoiUngId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,taiKhoanDoiUngChaId LONG,soHieu VARCHAR(75) null,ten VARCHAR(75) null,dienGiaiTheoDoi VARCHAR(75) null,loaiTaiKhoan INTEGER,hoatDong BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table dm_taikhoandoiung";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taiKhoanDoiUng.soHieu ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY dm_taikhoandoiung.soHieu ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.TaiKhoanDoiUng"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.TaiKhoanDoiUng"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.TaiKhoanDoiUng"),
		true);

	public static final long HOATDONG_COLUMN_BITMASK = 1L;

	public static final long LOAITAIKHOAN_COLUMN_BITMASK = 2L;

	public static final long SOHIEU_COLUMN_BITMASK = 4L;

	public static final long TAIKHOANDOIUNGCHAID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TaiKhoanDoiUng toModel(TaiKhoanDoiUngSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TaiKhoanDoiUng model = new TaiKhoanDoiUngImpl();

		model.setTaiKhoanDoiUngId(soapModel.getTaiKhoanDoiUngId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTaiKhoanDoiUngChaId(soapModel.getTaiKhoanDoiUngChaId());
		model.setSoHieu(soapModel.getSoHieu());
		model.setTen(soapModel.getTen());
		model.setDienGiaiTheoDoi(soapModel.getDienGiaiTheoDoi());
		model.setLoaiTaiKhoan(soapModel.getLoaiTaiKhoan());
		model.setHoatDong(soapModel.getHoatDong());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TaiKhoanDoiUng> toModels(
		TaiKhoanDoiUngSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<TaiKhoanDoiUng> models = new ArrayList<TaiKhoanDoiUng>(
			soapModels.length);

		for (TaiKhoanDoiUngSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.TaiKhoanDoiUng"));

	public TaiKhoanDoiUngModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taiKhoanDoiUngId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaiKhoanDoiUngId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taiKhoanDoiUngId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaiKhoanDoiUng.class;
	}

	@Override
	public String getModelClassName() {
		return TaiKhoanDoiUng.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaiKhoanDoiUng, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaiKhoanDoiUng, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaiKhoanDoiUng, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TaiKhoanDoiUng)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaiKhoanDoiUng, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaiKhoanDoiUng, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaiKhoanDoiUng)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaiKhoanDoiUng, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaiKhoanDoiUng, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TaiKhoanDoiUng, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TaiKhoanDoiUng, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TaiKhoanDoiUng, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TaiKhoanDoiUng, Object>>();
		Map<String, BiConsumer<TaiKhoanDoiUng, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TaiKhoanDoiUng, ?>>();

		attributeGetterFunctions.put(
			"taiKhoanDoiUngId",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getTaiKhoanDoiUngId();
				}

			});
		attributeSetterBiConsumers.put(
			"taiKhoanDoiUngId",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object taiKhoanDoiUngId) {

					taiKhoanDoiUng.setTaiKhoanDoiUngId((Long)taiKhoanDoiUngId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object companyId) {

					taiKhoanDoiUng.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object groupId) {

					taiKhoanDoiUng.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object userId) {

					taiKhoanDoiUng.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object userName) {

					taiKhoanDoiUng.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object createDate) {

					taiKhoanDoiUng.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object modifiedDate) {

					taiKhoanDoiUng.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"taiKhoanDoiUngChaId",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getTaiKhoanDoiUngChaId();
				}

			});
		attributeSetterBiConsumers.put(
			"taiKhoanDoiUngChaId",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object taiKhoanDoiUngChaId) {

					taiKhoanDoiUng.setTaiKhoanDoiUngChaId(
						(Long)taiKhoanDoiUngChaId);
				}

			});
		attributeGetterFunctions.put(
			"soHieu",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getSoHieu();
				}

			});
		attributeSetterBiConsumers.put(
			"soHieu",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object soHieu) {

					taiKhoanDoiUng.setSoHieu((String)soHieu);
				}

			});
		attributeGetterFunctions.put(
			"ten",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getTen();
				}

			});
		attributeSetterBiConsumers.put(
			"ten",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(TaiKhoanDoiUng taiKhoanDoiUng, Object ten) {
					taiKhoanDoiUng.setTen((String)ten);
				}

			});
		attributeGetterFunctions.put(
			"dienGiaiTheoDoi",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getDienGiaiTheoDoi();
				}

			});
		attributeSetterBiConsumers.put(
			"dienGiaiTheoDoi",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object dienGiaiTheoDoi) {

					taiKhoanDoiUng.setDienGiaiTheoDoi((String)dienGiaiTheoDoi);
				}

			});
		attributeGetterFunctions.put(
			"loaiTaiKhoan",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getLoaiTaiKhoan();
				}

			});
		attributeSetterBiConsumers.put(
			"loaiTaiKhoan",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object loaiTaiKhoan) {

					taiKhoanDoiUng.setLoaiTaiKhoan((Integer)loaiTaiKhoan);
				}

			});
		attributeGetterFunctions.put(
			"hoatDong",
			new Function<TaiKhoanDoiUng, Object>() {

				@Override
				public Object apply(TaiKhoanDoiUng taiKhoanDoiUng) {
					return taiKhoanDoiUng.getHoatDong();
				}

			});
		attributeSetterBiConsumers.put(
			"hoatDong",
			new BiConsumer<TaiKhoanDoiUng, Object>() {

				@Override
				public void accept(
					TaiKhoanDoiUng taiKhoanDoiUng, Object hoatDong) {

					taiKhoanDoiUng.setHoatDong((Boolean)hoatDong);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTaiKhoanDoiUngId() {
		return _taiKhoanDoiUngId;
	}

	@Override
	public void setTaiKhoanDoiUngId(long taiKhoanDoiUngId) {
		_taiKhoanDoiUngId = taiKhoanDoiUngId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getTaiKhoanDoiUngChaId() {
		return _taiKhoanDoiUngChaId;
	}

	@Override
	public void setTaiKhoanDoiUngChaId(long taiKhoanDoiUngChaId) {
		_columnBitmask |= TAIKHOANDOIUNGCHAID_COLUMN_BITMASK;

		if (!_setOriginalTaiKhoanDoiUngChaId) {
			_setOriginalTaiKhoanDoiUngChaId = true;

			_originalTaiKhoanDoiUngChaId = _taiKhoanDoiUngChaId;
		}

		_taiKhoanDoiUngChaId = taiKhoanDoiUngChaId;
	}

	public long getOriginalTaiKhoanDoiUngChaId() {
		return _originalTaiKhoanDoiUngChaId;
	}

	@JSON
	@Override
	public String getSoHieu() {
		if (_soHieu == null) {
			return "";
		}
		else {
			return _soHieu;
		}
	}

	@Override
	public void setSoHieu(String soHieu) {
		_columnBitmask = -1L;

		if (_originalSoHieu == null) {
			_originalSoHieu = _soHieu;
		}

		_soHieu = soHieu;
	}

	public String getOriginalSoHieu() {
		return GetterUtil.getString(_originalSoHieu);
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_ten = ten;
	}

	@JSON
	@Override
	public String getDienGiaiTheoDoi() {
		if (_dienGiaiTheoDoi == null) {
			return "";
		}
		else {
			return _dienGiaiTheoDoi;
		}
	}

	@Override
	public void setDienGiaiTheoDoi(String dienGiaiTheoDoi) {
		_dienGiaiTheoDoi = dienGiaiTheoDoi;
	}

	@JSON
	@Override
	public int getLoaiTaiKhoan() {
		return _loaiTaiKhoan;
	}

	@Override
	public void setLoaiTaiKhoan(int loaiTaiKhoan) {
		_columnBitmask |= LOAITAIKHOAN_COLUMN_BITMASK;

		if (!_setOriginalLoaiTaiKhoan) {
			_setOriginalLoaiTaiKhoan = true;

			_originalLoaiTaiKhoan = _loaiTaiKhoan;
		}

		_loaiTaiKhoan = loaiTaiKhoan;
	}

	public int getOriginalLoaiTaiKhoan() {
		return _originalLoaiTaiKhoan;
	}

	@JSON
	@Override
	public Boolean getHoatDong() {
		return _hoatDong;
	}

	@Override
	public void setHoatDong(Boolean hoatDong) {
		_columnBitmask |= HOATDONG_COLUMN_BITMASK;

		if (!_setOriginalHoatDong) {
			_setOriginalHoatDong = true;

			_originalHoatDong = _hoatDong;
		}

		_hoatDong = hoatDong;
	}

	public Boolean getOriginalHoatDong() {
		return _originalHoatDong;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TaiKhoanDoiUng.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaiKhoanDoiUng toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TaiKhoanDoiUng)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaiKhoanDoiUngImpl taiKhoanDoiUngImpl = new TaiKhoanDoiUngImpl();

		taiKhoanDoiUngImpl.setTaiKhoanDoiUngId(getTaiKhoanDoiUngId());
		taiKhoanDoiUngImpl.setCompanyId(getCompanyId());
		taiKhoanDoiUngImpl.setGroupId(getGroupId());
		taiKhoanDoiUngImpl.setUserId(getUserId());
		taiKhoanDoiUngImpl.setUserName(getUserName());
		taiKhoanDoiUngImpl.setCreateDate(getCreateDate());
		taiKhoanDoiUngImpl.setModifiedDate(getModifiedDate());
		taiKhoanDoiUngImpl.setTaiKhoanDoiUngChaId(getTaiKhoanDoiUngChaId());
		taiKhoanDoiUngImpl.setSoHieu(getSoHieu());
		taiKhoanDoiUngImpl.setTen(getTen());
		taiKhoanDoiUngImpl.setDienGiaiTheoDoi(getDienGiaiTheoDoi());
		taiKhoanDoiUngImpl.setLoaiTaiKhoan(getLoaiTaiKhoan());
		taiKhoanDoiUngImpl.setHoatDong(getHoatDong());

		taiKhoanDoiUngImpl.resetOriginalValues();

		return taiKhoanDoiUngImpl;
	}

	@Override
	public int compareTo(TaiKhoanDoiUng taiKhoanDoiUng) {
		int value = 0;

		value = getSoHieu().compareTo(taiKhoanDoiUng.getSoHieu());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaiKhoanDoiUng)) {
			return false;
		}

		TaiKhoanDoiUng taiKhoanDoiUng = (TaiKhoanDoiUng)obj;

		long primaryKey = taiKhoanDoiUng.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TaiKhoanDoiUngModelImpl taiKhoanDoiUngModelImpl = this;

		taiKhoanDoiUngModelImpl._setModifiedDate = false;

		taiKhoanDoiUngModelImpl._originalTaiKhoanDoiUngChaId =
			taiKhoanDoiUngModelImpl._taiKhoanDoiUngChaId;

		taiKhoanDoiUngModelImpl._setOriginalTaiKhoanDoiUngChaId = false;

		taiKhoanDoiUngModelImpl._originalSoHieu =
			taiKhoanDoiUngModelImpl._soHieu;

		taiKhoanDoiUngModelImpl._originalLoaiTaiKhoan =
			taiKhoanDoiUngModelImpl._loaiTaiKhoan;

		taiKhoanDoiUngModelImpl._setOriginalLoaiTaiKhoan = false;

		taiKhoanDoiUngModelImpl._originalHoatDong =
			taiKhoanDoiUngModelImpl._hoatDong;

		taiKhoanDoiUngModelImpl._setOriginalHoatDong = false;

		taiKhoanDoiUngModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaiKhoanDoiUng> toCacheModel() {
		TaiKhoanDoiUngCacheModel taiKhoanDoiUngCacheModel =
			new TaiKhoanDoiUngCacheModel();

		taiKhoanDoiUngCacheModel.taiKhoanDoiUngId = getTaiKhoanDoiUngId();

		taiKhoanDoiUngCacheModel.companyId = getCompanyId();

		taiKhoanDoiUngCacheModel.groupId = getGroupId();

		taiKhoanDoiUngCacheModel.userId = getUserId();

		taiKhoanDoiUngCacheModel.userName = getUserName();

		String userName = taiKhoanDoiUngCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			taiKhoanDoiUngCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			taiKhoanDoiUngCacheModel.createDate = createDate.getTime();
		}
		else {
			taiKhoanDoiUngCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taiKhoanDoiUngCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taiKhoanDoiUngCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taiKhoanDoiUngCacheModel.taiKhoanDoiUngChaId = getTaiKhoanDoiUngChaId();

		taiKhoanDoiUngCacheModel.soHieu = getSoHieu();

		String soHieu = taiKhoanDoiUngCacheModel.soHieu;

		if ((soHieu != null) && (soHieu.length() == 0)) {
			taiKhoanDoiUngCacheModel.soHieu = null;
		}

		taiKhoanDoiUngCacheModel.ten = getTen();

		String ten = taiKhoanDoiUngCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			taiKhoanDoiUngCacheModel.ten = null;
		}

		taiKhoanDoiUngCacheModel.dienGiaiTheoDoi = getDienGiaiTheoDoi();

		String dienGiaiTheoDoi = taiKhoanDoiUngCacheModel.dienGiaiTheoDoi;

		if ((dienGiaiTheoDoi != null) && (dienGiaiTheoDoi.length() == 0)) {
			taiKhoanDoiUngCacheModel.dienGiaiTheoDoi = null;
		}

		taiKhoanDoiUngCacheModel.loaiTaiKhoan = getLoaiTaiKhoan();

		taiKhoanDoiUngCacheModel.hoatDong = getHoatDong();

		return taiKhoanDoiUngCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaiKhoanDoiUng, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaiKhoanDoiUng, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaiKhoanDoiUng, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TaiKhoanDoiUng)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TaiKhoanDoiUng, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TaiKhoanDoiUng, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaiKhoanDoiUng, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TaiKhoanDoiUng)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		TaiKhoanDoiUng.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		TaiKhoanDoiUng.class, ModelWrapper.class
	};

	private long _taiKhoanDoiUngId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _taiKhoanDoiUngChaId;
	private long _originalTaiKhoanDoiUngChaId;
	private boolean _setOriginalTaiKhoanDoiUngChaId;
	private String _soHieu;
	private String _originalSoHieu;
	private String _ten;
	private String _dienGiaiTheoDoi;
	private int _loaiTaiKhoan;
	private int _originalLoaiTaiKhoan;
	private boolean _setOriginalLoaiTaiKhoan;
	private Boolean _hoatDong;
	private Boolean _originalHoatDong;
	private boolean _setOriginalHoatDong;
	private long _columnBitmask;
	private TaiKhoanDoiUng _escapedModel;

}