/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.mb.model.TaiSanThueChap;
import com.mb.model.TaiSanThueChapModel;
import com.mb.model.TaiSanThueChapSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TaiSanThueChap service. Represents a row in the &quot;mb_taisaithuechap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TaiSanThueChapModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaiSanThueChapImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaiSanThueChapImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TaiSanThueChapModelImpl
	extends BaseModelImpl<TaiSanThueChap> implements TaiSanThueChapModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tai san thue chap model instance should use the <code>TaiSanThueChap</code> interface instead.
	 */
	public static final String TABLE_NAME = "mb_taisaithuechap";

	public static final Object[][] TABLE_COLUMNS = {
		{"taiSanThueChapId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"phatVayId", Types.BIGINT},
		{"soKU", Types.VARCHAR}, {"maKhachHang", Types.VARCHAR},
		{"loaiTaiSanId", Types.BIGINT}, {"giaTriTaiSan", Types.DOUBLE},
		{"thongTinTaiSan", Types.VARCHAR}, {"ten", Types.VARCHAR},
		{"ghiChu", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("taiSanThueChapId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("phatVayId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("soKU", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("maKhachHang", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loaiTaiSanId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("giaTriTaiSan", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("thongTinTaiSan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ghiChu", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table mb_taisaithuechap (taiSanThueChapId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,phatVayId LONG,soKU VARCHAR(75) null,maKhachHang VARCHAR(75) null,loaiTaiSanId LONG,giaTriTaiSan DOUBLE,thongTinTaiSan VARCHAR(75) null,ten VARCHAR(75) null,ghiChu VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table mb_taisaithuechap";

	public static final String ORDER_BY_JPQL =
		" ORDER BY taiSanThueChap.taiSanThueChapId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY mb_taisaithuechap.taiSanThueChapId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.mb.model.TaiSanThueChap"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.mb.model.TaiSanThueChap"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.mb.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.mb.model.TaiSanThueChap"),
		true);

	public static final long PHATVAYID_COLUMN_BITMASK = 1L;

	public static final long TAISANTHUECHAPID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TaiSanThueChap toModel(TaiSanThueChapSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TaiSanThueChap model = new TaiSanThueChapImpl();

		model.setTaiSanThueChapId(soapModel.getTaiSanThueChapId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPhatVayId(soapModel.getPhatVayId());
		model.setSoKU(soapModel.getSoKU());
		model.setMaKhachHang(soapModel.getMaKhachHang());
		model.setLoaiTaiSanId(soapModel.getLoaiTaiSanId());
		model.setGiaTriTaiSan(soapModel.getGiaTriTaiSan());
		model.setThongTinTaiSan(soapModel.getThongTinTaiSan());
		model.setTen(soapModel.getTen());
		model.setGhiChu(soapModel.getGhiChu());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TaiSanThueChap> toModels(
		TaiSanThueChapSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<TaiSanThueChap> models = new ArrayList<TaiSanThueChap>(
			soapModels.length);

		for (TaiSanThueChapSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.mb.service.util.ServiceProps.get(
			"lock.expiration.time.com.mb.model.TaiSanThueChap"));

	public TaiSanThueChapModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _taiSanThueChapId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTaiSanThueChapId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _taiSanThueChapId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TaiSanThueChap.class;
	}

	@Override
	public String getModelClassName() {
		return TaiSanThueChap.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TaiSanThueChap, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TaiSanThueChap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaiSanThueChap, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TaiSanThueChap)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TaiSanThueChap, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TaiSanThueChap, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TaiSanThueChap)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TaiSanThueChap, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TaiSanThueChap, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TaiSanThueChap, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TaiSanThueChap, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TaiSanThueChap, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TaiSanThueChap, Object>>();
		Map<String, BiConsumer<TaiSanThueChap, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TaiSanThueChap, ?>>();

		attributeGetterFunctions.put(
			"taiSanThueChapId",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getTaiSanThueChapId();
				}

			});
		attributeSetterBiConsumers.put(
			"taiSanThueChapId",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object taiSanThueChapId) {

					taiSanThueChap.setTaiSanThueChapId((Long)taiSanThueChapId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object companyId) {

					taiSanThueChap.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object groupId) {

					taiSanThueChap.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object userId) {

					taiSanThueChap.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object userName) {

					taiSanThueChap.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object createDate) {

					taiSanThueChap.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object modifiedDate) {

					taiSanThueChap.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"phatVayId",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getPhatVayId();
				}

			});
		attributeSetterBiConsumers.put(
			"phatVayId",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object phatVayId) {

					taiSanThueChap.setPhatVayId((Long)phatVayId);
				}

			});
		attributeGetterFunctions.put(
			"soKU",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getSoKU();
				}

			});
		attributeSetterBiConsumers.put(
			"soKU",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(TaiSanThueChap taiSanThueChap, Object soKU) {
					taiSanThueChap.setSoKU((String)soKU);
				}

			});
		attributeGetterFunctions.put(
			"maKhachHang",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getMaKhachHang();
				}

			});
		attributeSetterBiConsumers.put(
			"maKhachHang",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object maKhachHang) {

					taiSanThueChap.setMaKhachHang((String)maKhachHang);
				}

			});
		attributeGetterFunctions.put(
			"loaiTaiSanId",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getLoaiTaiSanId();
				}

			});
		attributeSetterBiConsumers.put(
			"loaiTaiSanId",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object loaiTaiSanId) {

					taiSanThueChap.setLoaiTaiSanId((Long)loaiTaiSanId);
				}

			});
		attributeGetterFunctions.put(
			"giaTriTaiSan",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getGiaTriTaiSan();
				}

			});
		attributeSetterBiConsumers.put(
			"giaTriTaiSan",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object giaTriTaiSan) {

					taiSanThueChap.setGiaTriTaiSan((Double)giaTriTaiSan);
				}

			});
		attributeGetterFunctions.put(
			"thongTinTaiSan",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getThongTinTaiSan();
				}

			});
		attributeSetterBiConsumers.put(
			"thongTinTaiSan",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object thongTinTaiSan) {

					taiSanThueChap.setThongTinTaiSan((String)thongTinTaiSan);
				}

			});
		attributeGetterFunctions.put(
			"ten",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getTen();
				}

			});
		attributeSetterBiConsumers.put(
			"ten",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(TaiSanThueChap taiSanThueChap, Object ten) {
					taiSanThueChap.setTen((String)ten);
				}

			});
		attributeGetterFunctions.put(
			"ghiChu",
			new Function<TaiSanThueChap, Object>() {

				@Override
				public Object apply(TaiSanThueChap taiSanThueChap) {
					return taiSanThueChap.getGhiChu();
				}

			});
		attributeSetterBiConsumers.put(
			"ghiChu",
			new BiConsumer<TaiSanThueChap, Object>() {

				@Override
				public void accept(
					TaiSanThueChap taiSanThueChap, Object ghiChu) {

					taiSanThueChap.setGhiChu((String)ghiChu);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTaiSanThueChapId() {
		return _taiSanThueChapId;
	}

	@Override
	public void setTaiSanThueChapId(long taiSanThueChapId) {
		_columnBitmask = -1L;

		_taiSanThueChapId = taiSanThueChapId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPhatVayId() {
		return _phatVayId;
	}

	@Override
	public void setPhatVayId(long phatVayId) {
		_columnBitmask |= PHATVAYID_COLUMN_BITMASK;

		if (!_setOriginalPhatVayId) {
			_setOriginalPhatVayId = true;

			_originalPhatVayId = _phatVayId;
		}

		_phatVayId = phatVayId;
	}

	public long getOriginalPhatVayId() {
		return _originalPhatVayId;
	}

	@JSON
	@Override
	public String getSoKU() {
		if (_soKU == null) {
			return "";
		}
		else {
			return _soKU;
		}
	}

	@Override
	public void setSoKU(String soKU) {
		_soKU = soKU;
	}

	@JSON
	@Override
	public String getMaKhachHang() {
		if (_maKhachHang == null) {
			return "";
		}
		else {
			return _maKhachHang;
		}
	}

	@Override
	public void setMaKhachHang(String maKhachHang) {
		_maKhachHang = maKhachHang;
	}

	@JSON
	@Override
	public long getLoaiTaiSanId() {
		return _loaiTaiSanId;
	}

	@Override
	public void setLoaiTaiSanId(long loaiTaiSanId) {
		_loaiTaiSanId = loaiTaiSanId;
	}

	@JSON
	@Override
	public Double getGiaTriTaiSan() {
		return _giaTriTaiSan;
	}

	@Override
	public void setGiaTriTaiSan(Double giaTriTaiSan) {
		_giaTriTaiSan = giaTriTaiSan;
	}

	@JSON
	@Override
	public String getThongTinTaiSan() {
		if (_thongTinTaiSan == null) {
			return "";
		}
		else {
			return _thongTinTaiSan;
		}
	}

	@Override
	public void setThongTinTaiSan(String thongTinTaiSan) {
		_thongTinTaiSan = thongTinTaiSan;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		_ten = ten;
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return "";
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TaiSanThueChap.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TaiSanThueChap toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TaiSanThueChap)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaiSanThueChapImpl taiSanThueChapImpl = new TaiSanThueChapImpl();

		taiSanThueChapImpl.setTaiSanThueChapId(getTaiSanThueChapId());
		taiSanThueChapImpl.setCompanyId(getCompanyId());
		taiSanThueChapImpl.setGroupId(getGroupId());
		taiSanThueChapImpl.setUserId(getUserId());
		taiSanThueChapImpl.setUserName(getUserName());
		taiSanThueChapImpl.setCreateDate(getCreateDate());
		taiSanThueChapImpl.setModifiedDate(getModifiedDate());
		taiSanThueChapImpl.setPhatVayId(getPhatVayId());
		taiSanThueChapImpl.setSoKU(getSoKU());
		taiSanThueChapImpl.setMaKhachHang(getMaKhachHang());
		taiSanThueChapImpl.setLoaiTaiSanId(getLoaiTaiSanId());
		taiSanThueChapImpl.setGiaTriTaiSan(getGiaTriTaiSan());
		taiSanThueChapImpl.setThongTinTaiSan(getThongTinTaiSan());
		taiSanThueChapImpl.setTen(getTen());
		taiSanThueChapImpl.setGhiChu(getGhiChu());

		taiSanThueChapImpl.resetOriginalValues();

		return taiSanThueChapImpl;
	}

	@Override
	public int compareTo(TaiSanThueChap taiSanThueChap) {
		int value = 0;

		if (getTaiSanThueChapId() < taiSanThueChap.getTaiSanThueChapId()) {
			value = -1;
		}
		else if (getTaiSanThueChapId() > taiSanThueChap.getTaiSanThueChapId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaiSanThueChap)) {
			return false;
		}

		TaiSanThueChap taiSanThueChap = (TaiSanThueChap)obj;

		long primaryKey = taiSanThueChap.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TaiSanThueChapModelImpl taiSanThueChapModelImpl = this;

		taiSanThueChapModelImpl._setModifiedDate = false;

		taiSanThueChapModelImpl._originalPhatVayId =
			taiSanThueChapModelImpl._phatVayId;

		taiSanThueChapModelImpl._setOriginalPhatVayId = false;

		taiSanThueChapModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TaiSanThueChap> toCacheModel() {
		TaiSanThueChapCacheModel taiSanThueChapCacheModel =
			new TaiSanThueChapCacheModel();

		taiSanThueChapCacheModel.taiSanThueChapId = getTaiSanThueChapId();

		taiSanThueChapCacheModel.companyId = getCompanyId();

		taiSanThueChapCacheModel.groupId = getGroupId();

		taiSanThueChapCacheModel.userId = getUserId();

		taiSanThueChapCacheModel.userName = getUserName();

		String userName = taiSanThueChapCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			taiSanThueChapCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			taiSanThueChapCacheModel.createDate = createDate.getTime();
		}
		else {
			taiSanThueChapCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			taiSanThueChapCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			taiSanThueChapCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		taiSanThueChapCacheModel.phatVayId = getPhatVayId();

		taiSanThueChapCacheModel.soKU = getSoKU();

		String soKU = taiSanThueChapCacheModel.soKU;

		if ((soKU != null) && (soKU.length() == 0)) {
			taiSanThueChapCacheModel.soKU = null;
		}

		taiSanThueChapCacheModel.maKhachHang = getMaKhachHang();

		String maKhachHang = taiSanThueChapCacheModel.maKhachHang;

		if ((maKhachHang != null) && (maKhachHang.length() == 0)) {
			taiSanThueChapCacheModel.maKhachHang = null;
		}

		taiSanThueChapCacheModel.loaiTaiSanId = getLoaiTaiSanId();

		taiSanThueChapCacheModel.giaTriTaiSan = getGiaTriTaiSan();

		taiSanThueChapCacheModel.thongTinTaiSan = getThongTinTaiSan();

		String thongTinTaiSan = taiSanThueChapCacheModel.thongTinTaiSan;

		if ((thongTinTaiSan != null) && (thongTinTaiSan.length() == 0)) {
			taiSanThueChapCacheModel.thongTinTaiSan = null;
		}

		taiSanThueChapCacheModel.ten = getTen();

		String ten = taiSanThueChapCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			taiSanThueChapCacheModel.ten = null;
		}

		taiSanThueChapCacheModel.ghiChu = getGhiChu();

		String ghiChu = taiSanThueChapCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			taiSanThueChapCacheModel.ghiChu = null;
		}

		return taiSanThueChapCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TaiSanThueChap, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TaiSanThueChap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaiSanThueChap, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TaiSanThueChap)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TaiSanThueChap, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TaiSanThueChap, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TaiSanThueChap, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TaiSanThueChap)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		TaiSanThueChap.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		TaiSanThueChap.class, ModelWrapper.class
	};

	private long _taiSanThueChapId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _phatVayId;
	private long _originalPhatVayId;
	private boolean _setOriginalPhatVayId;
	private String _soKU;
	private String _maKhachHang;
	private long _loaiTaiSanId;
	private Double _giaTriTaiSan;
	private String _thongTinTaiSan;
	private String _ten;
	private String _ghiChu;
	private long _columnBitmask;
	private TaiSanThueChap _escapedModel;

}