/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CauHinhThuTienTet service. Represents a row in the &quot;dm_cauhinhthutientet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.CauHinhThuTienTetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.CauHinhThuTienTetImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CauHinhThuTienTet
 * @generated
 */
@ProviderType
public interface CauHinhThuTienTetModel extends BaseModel<CauHinhThuTienTet> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cau hinh thu tien tet model instance should use the {@link CauHinhThuTienTet} interface instead.
	 */

	/**
	 * Returns the primary key of this cau hinh thu tien tet.
	 *
	 * @return the primary key of this cau hinh thu tien tet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cau hinh thu tien tet.
	 *
	 * @param primaryKey the primary key of this cau hinh thu tien tet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cau hinh thu tien tet ID of this cau hinh thu tien tet.
	 *
	 * @return the cau hinh thu tien tet ID of this cau hinh thu tien tet
	 */
	public long getCauHinhThuTienTetId();

	/**
	 * Sets the cau hinh thu tien tet ID of this cau hinh thu tien tet.
	 *
	 * @param cauHinhThuTienTetId the cau hinh thu tien tet ID of this cau hinh thu tien tet
	 */
	public void setCauHinhThuTienTetId(long cauHinhThuTienTetId);

	/**
	 * Returns the nam of this cau hinh thu tien tet.
	 *
	 * @return the nam of this cau hinh thu tien tet
	 */
	public int getNam();

	/**
	 * Sets the nam of this cau hinh thu tien tet.
	 *
	 * @param nam the nam of this cau hinh thu tien tet
	 */
	public void setNam(int nam);

	/**
	 * Returns the ngay bat dau of this cau hinh thu tien tet.
	 *
	 * @return the ngay bat dau of this cau hinh thu tien tet
	 */
	public Date getNgayBatDau();

	/**
	 * Sets the ngay bat dau of this cau hinh thu tien tet.
	 *
	 * @param ngayBatDau the ngay bat dau of this cau hinh thu tien tet
	 */
	public void setNgayBatDau(Date ngayBatDau);

	/**
	 * Returns the ngay ket thuc of this cau hinh thu tien tet.
	 *
	 * @return the ngay ket thuc of this cau hinh thu tien tet
	 */
	public Date getNgayKetThuc();

	/**
	 * Sets the ngay ket thuc of this cau hinh thu tien tet.
	 *
	 * @param ngayKetThuc the ngay ket thuc of this cau hinh thu tien tet
	 */
	public void setNgayKetThuc(Date ngayKetThuc);

	/**
	 * Returns the so ngay of this cau hinh thu tien tet.
	 *
	 * @return the so ngay of this cau hinh thu tien tet
	 */
	public int getSoNgay();

	/**
	 * Sets the so ngay of this cau hinh thu tien tet.
	 *
	 * @param soNgay the so ngay of this cau hinh thu tien tet
	 */
	public void setSoNgay(int soNgay);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CauHinhThuTienTet cauHinhThuTienTet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CauHinhThuTienTet> toCacheModel();

	@Override
	public CauHinhThuTienTet toEscapedModel();

	@Override
	public CauHinhThuTienTet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}