/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CauHinhThuTienTruoc service. Represents a row in the &quot;dm_cauhinhthutientruoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.CauHinhThuTienTruocModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.CauHinhThuTienTruocImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CauHinhThuTienTruoc
 * @generated
 */
@ProviderType
public interface CauHinhThuTienTruocModel
	extends BaseModel<CauHinhThuTienTruoc>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cau hinh thu tien truoc model instance should use the {@link CauHinhThuTienTruoc} interface instead.
	 */

	/**
	 * Returns the primary key of this cau hinh thu tien truoc.
	 *
	 * @return the primary key of this cau hinh thu tien truoc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cau hinh thu tien truoc.
	 *
	 * @param primaryKey the primary key of this cau hinh thu tien truoc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cau hinh thu tien truoc ID of this cau hinh thu tien truoc.
	 *
	 * @return the cau hinh thu tien truoc ID of this cau hinh thu tien truoc
	 */
	public long getCauHinhThuTienTruocId();

	/**
	 * Sets the cau hinh thu tien truoc ID of this cau hinh thu tien truoc.
	 *
	 * @param cauHinhThuTienTruocId the cau hinh thu tien truoc ID of this cau hinh thu tien truoc
	 */
	public void setCauHinhThuTienTruocId(long cauHinhThuTienTruocId);

	/**
	 * Returns the company ID of this cau hinh thu tien truoc.
	 *
	 * @return the company ID of this cau hinh thu tien truoc
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cau hinh thu tien truoc.
	 *
	 * @param companyId the company ID of this cau hinh thu tien truoc
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this cau hinh thu tien truoc.
	 *
	 * @return the group ID of this cau hinh thu tien truoc
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this cau hinh thu tien truoc.
	 *
	 * @param groupId the group ID of this cau hinh thu tien truoc
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this cau hinh thu tien truoc.
	 *
	 * @return the user ID of this cau hinh thu tien truoc
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cau hinh thu tien truoc.
	 *
	 * @param userId the user ID of this cau hinh thu tien truoc
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cau hinh thu tien truoc.
	 *
	 * @return the user uuid of this cau hinh thu tien truoc
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cau hinh thu tien truoc.
	 *
	 * @param userUuid the user uuid of this cau hinh thu tien truoc
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cau hinh thu tien truoc.
	 *
	 * @return the user name of this cau hinh thu tien truoc
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cau hinh thu tien truoc.
	 *
	 * @param userName the user name of this cau hinh thu tien truoc
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cau hinh thu tien truoc.
	 *
	 * @return the create date of this cau hinh thu tien truoc
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cau hinh thu tien truoc.
	 *
	 * @param createDate the create date of this cau hinh thu tien truoc
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cau hinh thu tien truoc.
	 *
	 * @return the modified date of this cau hinh thu tien truoc
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cau hinh thu tien truoc.
	 *
	 * @param modifiedDate the modified date of this cau hinh thu tien truoc
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nam of this cau hinh thu tien truoc.
	 *
	 * @return the nam of this cau hinh thu tien truoc
	 */
	public int getNam();

	/**
	 * Sets the nam of this cau hinh thu tien truoc.
	 *
	 * @param nam the nam of this cau hinh thu tien truoc
	 */
	public void setNam(int nam);

	/**
	 * Returns the ngay tu of this cau hinh thu tien truoc.
	 *
	 * @return the ngay tu of this cau hinh thu tien truoc
	 */
	public Date getNgayTu();

	/**
	 * Sets the ngay tu of this cau hinh thu tien truoc.
	 *
	 * @param ngayTu the ngay tu of this cau hinh thu tien truoc
	 */
	public void setNgayTu(Date ngayTu);

	/**
	 * Returns the ngay den of this cau hinh thu tien truoc.
	 *
	 * @return the ngay den of this cau hinh thu tien truoc
	 */
	public Date getNgayDen();

	/**
	 * Sets the ngay den of this cau hinh thu tien truoc.
	 *
	 * @param ngayDen the ngay den of this cau hinh thu tien truoc
	 */
	public void setNgayDen(Date ngayDen);

	/**
	 * Returns the hoat dong of this cau hinh thu tien truoc.
	 *
	 * @return the hoat dong of this cau hinh thu tien truoc
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this cau hinh thu tien truoc.
	 *
	 * @param hoatDong the hoat dong of this cau hinh thu tien truoc
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CauHinhThuTienTruoc cauHinhThuTienTruoc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CauHinhThuTienTruoc> toCacheModel();

	@Override
	public CauHinhThuTienTruoc toEscapedModel();

	@Override
	public CauHinhThuTienTruoc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}