/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChiNhanh service. Represents a row in the &quot;dm_chinhanh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.ChiNhanhModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.ChiNhanhImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChiNhanh
 * @generated
 */
@ProviderType
public interface ChiNhanhModel
	extends BaseModel<ChiNhanh>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chi nhanh model instance should use the {@link ChiNhanh} interface instead.
	 */

	/**
	 * Returns the primary key of this chi nhanh.
	 *
	 * @return the primary key of this chi nhanh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chi nhanh.
	 *
	 * @param primaryKey the primary key of this chi nhanh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the chi nhanh ID of this chi nhanh.
	 *
	 * @return the chi nhanh ID of this chi nhanh
	 */
	public long getChiNhanhId();

	/**
	 * Sets the chi nhanh ID of this chi nhanh.
	 *
	 * @param chiNhanhId the chi nhanh ID of this chi nhanh
	 */
	public void setChiNhanhId(long chiNhanhId);

	/**
	 * Returns the company ID of this chi nhanh.
	 *
	 * @return the company ID of this chi nhanh
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this chi nhanh.
	 *
	 * @param companyId the company ID of this chi nhanh
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this chi nhanh.
	 *
	 * @return the group ID of this chi nhanh
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this chi nhanh.
	 *
	 * @param groupId the group ID of this chi nhanh
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this chi nhanh.
	 *
	 * @return the user ID of this chi nhanh
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this chi nhanh.
	 *
	 * @param userId the user ID of this chi nhanh
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this chi nhanh.
	 *
	 * @return the user uuid of this chi nhanh
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this chi nhanh.
	 *
	 * @param userUuid the user uuid of this chi nhanh
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this chi nhanh.
	 *
	 * @return the user name of this chi nhanh
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this chi nhanh.
	 *
	 * @param userName the user name of this chi nhanh
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this chi nhanh.
	 *
	 * @return the create date of this chi nhanh
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this chi nhanh.
	 *
	 * @param createDate the create date of this chi nhanh
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this chi nhanh.
	 *
	 * @return the modified date of this chi nhanh
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this chi nhanh.
	 *
	 * @param modifiedDate the modified date of this chi nhanh
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ma of this chi nhanh.
	 *
	 * @return the ma of this chi nhanh
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this chi nhanh.
	 *
	 * @param ma the ma of this chi nhanh
	 */
	public void setMa(String ma);

	/**
	 * Returns the ten of this chi nhanh.
	 *
	 * @return the ten of this chi nhanh
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this chi nhanh.
	 *
	 * @param ten the ten of this chi nhanh
	 */
	public void setTen(String ten);

	/**
	 * Returns the hoat dong of this chi nhanh.
	 *
	 * @return the hoat dong of this chi nhanh
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this chi nhanh.
	 *
	 * @param hoatDong the hoat dong of this chi nhanh
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ChiNhanh chiNhanh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ChiNhanh> toCacheModel();

	@Override
	public ChiNhanh toEscapedModel();

	@Override
	public ChiNhanh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}