/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DsPhieuTaiKhoan service. Represents a row in the &quot;ketoan_dsphieutaikhoan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.DsPhieuTaiKhoanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.DsPhieuTaiKhoanImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DsPhieuTaiKhoan
 * @generated
 */
@ProviderType
public interface DsPhieuTaiKhoanModel
	extends BaseModel<DsPhieuTaiKhoan>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ds phieu tai khoan model instance should use the {@link DsPhieuTaiKhoan} interface instead.
	 */

	/**
	 * Returns the primary key of this ds phieu tai khoan.
	 *
	 * @return the primary key of this ds phieu tai khoan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ds phieu tai khoan.
	 *
	 * @param primaryKey the primary key of this ds phieu tai khoan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ds phieu tai khoan ID of this ds phieu tai khoan.
	 *
	 * @return the ds phieu tai khoan ID of this ds phieu tai khoan
	 */
	public long getDsPhieuTaiKhoanId();

	/**
	 * Sets the ds phieu tai khoan ID of this ds phieu tai khoan.
	 *
	 * @param dsPhieuTaiKhoanId the ds phieu tai khoan ID of this ds phieu tai khoan
	 */
	public void setDsPhieuTaiKhoanId(long dsPhieuTaiKhoanId);

	/**
	 * Returns the company ID of this ds phieu tai khoan.
	 *
	 * @return the company ID of this ds phieu tai khoan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ds phieu tai khoan.
	 *
	 * @param companyId the company ID of this ds phieu tai khoan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this ds phieu tai khoan.
	 *
	 * @return the group ID of this ds phieu tai khoan
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ds phieu tai khoan.
	 *
	 * @param groupId the group ID of this ds phieu tai khoan
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this ds phieu tai khoan.
	 *
	 * @return the user ID of this ds phieu tai khoan
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ds phieu tai khoan.
	 *
	 * @param userId the user ID of this ds phieu tai khoan
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ds phieu tai khoan.
	 *
	 * @return the user uuid of this ds phieu tai khoan
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ds phieu tai khoan.
	 *
	 * @param userUuid the user uuid of this ds phieu tai khoan
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ds phieu tai khoan.
	 *
	 * @return the user name of this ds phieu tai khoan
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ds phieu tai khoan.
	 *
	 * @param userName the user name of this ds phieu tai khoan
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ds phieu tai khoan.
	 *
	 * @return the create date of this ds phieu tai khoan
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ds phieu tai khoan.
	 *
	 * @param createDate the create date of this ds phieu tai khoan
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ds phieu tai khoan.
	 *
	 * @return the modified date of this ds phieu tai khoan
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ds phieu tai khoan.
	 *
	 * @param modifiedDate the modified date of this ds phieu tai khoan
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the phieu ID of this ds phieu tai khoan.
	 *
	 * @return the phieu ID of this ds phieu tai khoan
	 */
	public long getPhieuId();

	/**
	 * Sets the phieu ID of this ds phieu tai khoan.
	 *
	 * @param phieuId the phieu ID of this ds phieu tai khoan
	 */
	public void setPhieuId(long phieuId);

	/**
	 * Returns the ngay chung tu of this ds phieu tai khoan.
	 *
	 * @return the ngay chung tu of this ds phieu tai khoan
	 */
	public Date getNgayChungTu();

	/**
	 * Sets the ngay chung tu of this ds phieu tai khoan.
	 *
	 * @param ngayChungTu the ngay chung tu of this ds phieu tai khoan
	 */
	public void setNgayChungTu(Date ngayChungTu);

	/**
	 * Returns the tai khoan doi ung ID of this ds phieu tai khoan.
	 *
	 * @return the tai khoan doi ung ID of this ds phieu tai khoan
	 */
	public long getTaiKhoanDoiUngId();

	/**
	 * Sets the tai khoan doi ung ID of this ds phieu tai khoan.
	 *
	 * @param taiKhoanDoiUngId the tai khoan doi ung ID of this ds phieu tai khoan
	 */
	public void setTaiKhoanDoiUngId(long taiKhoanDoiUngId);

	/**
	 * Returns the ma theo doi of this ds phieu tai khoan.
	 *
	 * @return the ma theo doi of this ds phieu tai khoan
	 */
	@AutoEscape
	public String getMaTheoDoi();

	/**
	 * Sets the ma theo doi of this ds phieu tai khoan.
	 *
	 * @param maTheoDoi the ma theo doi of this ds phieu tai khoan
	 */
	public void setMaTheoDoi(String maTheoDoi);

	/**
	 * Returns the dien giai theo doi of this ds phieu tai khoan.
	 *
	 * @return the dien giai theo doi of this ds phieu tai khoan
	 */
	@AutoEscape
	public String getDienGiaiTheoDoi();

	/**
	 * Sets the dien giai theo doi of this ds phieu tai khoan.
	 *
	 * @param dienGiaiTheoDoi the dien giai theo doi of this ds phieu tai khoan
	 */
	public void setDienGiaiTheoDoi(String dienGiaiTheoDoi);

	/**
	 * Returns the so tien of this ds phieu tai khoan.
	 *
	 * @return the so tien of this ds phieu tai khoan
	 */
	public Double getSoTien();

	/**
	 * Sets the so tien of this ds phieu tai khoan.
	 *
	 * @param soTien the so tien of this ds phieu tai khoan
	 */
	public void setSoTien(Double soTien);

	/**
	 * Returns the ten ctv of this ds phieu tai khoan.
	 *
	 * @return the ten ctv of this ds phieu tai khoan
	 */
	@AutoEscape
	public String getTenCTV();

	/**
	 * Sets the ten ctv of this ds phieu tai khoan.
	 *
	 * @param tenCTV the ten ctv of this ds phieu tai khoan
	 */
	public void setTenCTV(String tenCTV);

	/**
	 * Returns the ma ctv of this ds phieu tai khoan.
	 *
	 * @return the ma ctv of this ds phieu tai khoan
	 */
	@AutoEscape
	public String getMaCTV();

	/**
	 * Sets the ma ctv of this ds phieu tai khoan.
	 *
	 * @param maCTV the ma ctv of this ds phieu tai khoan
	 */
	public void setMaCTV(String maCTV);

	/**
	 * Returns the hoat dong of this ds phieu tai khoan.
	 *
	 * @return the hoat dong of this ds phieu tai khoan
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this ds phieu tai khoan.
	 *
	 * @param hoatDong the hoat dong of this ds phieu tai khoan
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DsPhieuTaiKhoan dsPhieuTaiKhoan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DsPhieuTaiKhoan> toCacheModel();

	@Override
	public DsPhieuTaiKhoan toEscapedModel();

	@Override
	public DsPhieuTaiKhoan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}