/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KhachHang service. Represents a row in the &quot;dm_khachhang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.KhachHangModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.KhachHangImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KhachHang
 * @generated
 */
@ProviderType
public interface KhachHangModel
	extends BaseModel<KhachHang>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a khach hang model instance should use the {@link KhachHang} interface instead.
	 */

	/**
	 * Returns the primary key of this khach hang.
	 *
	 * @return the primary key of this khach hang
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this khach hang.
	 *
	 * @param primaryKey the primary key of this khach hang
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the khach hang ID of this khach hang.
	 *
	 * @return the khach hang ID of this khach hang
	 */
	public long getKhachHangId();

	/**
	 * Sets the khach hang ID of this khach hang.
	 *
	 * @param khachHangId the khach hang ID of this khach hang
	 */
	public void setKhachHangId(long khachHangId);

	/**
	 * Returns the company ID of this khach hang.
	 *
	 * @return the company ID of this khach hang
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this khach hang.
	 *
	 * @param companyId the company ID of this khach hang
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this khach hang.
	 *
	 * @return the group ID of this khach hang
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this khach hang.
	 *
	 * @param groupId the group ID of this khach hang
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this khach hang.
	 *
	 * @return the user ID of this khach hang
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this khach hang.
	 *
	 * @param userId the user ID of this khach hang
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this khach hang.
	 *
	 * @return the user uuid of this khach hang
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this khach hang.
	 *
	 * @param userUuid the user uuid of this khach hang
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this khach hang.
	 *
	 * @return the user name of this khach hang
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this khach hang.
	 *
	 * @param userName the user name of this khach hang
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this khach hang.
	 *
	 * @return the create date of this khach hang
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this khach hang.
	 *
	 * @param createDate the create date of this khach hang
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this khach hang.
	 *
	 * @return the modified date of this khach hang
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this khach hang.
	 *
	 * @param modifiedDate the modified date of this khach hang
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ma ctv of this khach hang.
	 *
	 * @return the ma ctv of this khach hang
	 */
	@AutoEscape
	public String getMaCTV();

	/**
	 * Sets the ma ctv of this khach hang.
	 *
	 * @param maCTV the ma ctv of this khach hang
	 */
	public void setMaCTV(String maCTV);

	/**
	 * Returns the ma of this khach hang.
	 *
	 * @return the ma of this khach hang
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this khach hang.
	 *
	 * @param ma the ma of this khach hang
	 */
	public void setMa(String ma);

	/**
	 * Returns the ho ten of this khach hang.
	 *
	 * @return the ho ten of this khach hang
	 */
	@AutoEscape
	public String getHoTen();

	/**
	 * Sets the ho ten of this khach hang.
	 *
	 * @param hoTen the ho ten of this khach hang
	 */
	public void setHoTen(String hoTen);

	/**
	 * Returns the so cmnd of this khach hang.
	 *
	 * @return the so cmnd of this khach hang
	 */
	@AutoEscape
	public String getSoCMND();

	/**
	 * Sets the so cmnd of this khach hang.
	 *
	 * @param soCMND the so cmnd of this khach hang
	 */
	public void setSoCMND(String soCMND);

	/**
	 * Returns the dia chi of this khach hang.
	 *
	 * @return the dia chi of this khach hang
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this khach hang.
	 *
	 * @param diaChi the dia chi of this khach hang
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the hoat dong of this khach hang.
	 *
	 * @return the hoat dong of this khach hang
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this khach hang.
	 *
	 * @param hoatDong the hoat dong of this khach hang
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KhachHang khachHang);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KhachHang> toCacheModel();

	@Override
	public KhachHang toEscapedModel();

	@Override
	public KhachHang toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}