/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LichSuTaiKhoanDauKy service. Represents a row in the &quot;ketoan_lichsutaikhoandauky&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.LichSuTaiKhoanDauKyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.LichSuTaiKhoanDauKyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LichSuTaiKhoanDauKy
 * @generated
 */
@ProviderType
public interface LichSuTaiKhoanDauKyModel
	extends BaseModel<LichSuTaiKhoanDauKy>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lich su tai khoan dau ky model instance should use the {@link LichSuTaiKhoanDauKy} interface instead.
	 */

	/**
	 * Returns the primary key of this lich su tai khoan dau ky.
	 *
	 * @return the primary key of this lich su tai khoan dau ky
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lich su tai khoan dau ky.
	 *
	 * @param primaryKey the primary key of this lich su tai khoan dau ky
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lich su tai khoan dau ky ID of this lich su tai khoan dau ky.
	 *
	 * @return the lich su tai khoan dau ky ID of this lich su tai khoan dau ky
	 */
	public long getLichSuTaiKhoanDauKyId();

	/**
	 * Sets the lich su tai khoan dau ky ID of this lich su tai khoan dau ky.
	 *
	 * @param lichSuTaiKhoanDauKyId the lich su tai khoan dau ky ID of this lich su tai khoan dau ky
	 */
	public void setLichSuTaiKhoanDauKyId(long lichSuTaiKhoanDauKyId);

	/**
	 * Returns the company ID of this lich su tai khoan dau ky.
	 *
	 * @return the company ID of this lich su tai khoan dau ky
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lich su tai khoan dau ky.
	 *
	 * @param companyId the company ID of this lich su tai khoan dau ky
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this lich su tai khoan dau ky.
	 *
	 * @return the group ID of this lich su tai khoan dau ky
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lich su tai khoan dau ky.
	 *
	 * @param groupId the group ID of this lich su tai khoan dau ky
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lich su tai khoan dau ky.
	 *
	 * @return the user ID of this lich su tai khoan dau ky
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lich su tai khoan dau ky.
	 *
	 * @param userId the user ID of this lich su tai khoan dau ky
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lich su tai khoan dau ky.
	 *
	 * @return the user uuid of this lich su tai khoan dau ky
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lich su tai khoan dau ky.
	 *
	 * @param userUuid the user uuid of this lich su tai khoan dau ky
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lich su tai khoan dau ky.
	 *
	 * @return the user name of this lich su tai khoan dau ky
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lich su tai khoan dau ky.
	 *
	 * @param userName the user name of this lich su tai khoan dau ky
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lich su tai khoan dau ky.
	 *
	 * @return the create date of this lich su tai khoan dau ky
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lich su tai khoan dau ky.
	 *
	 * @param createDate the create date of this lich su tai khoan dau ky
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lich su tai khoan dau ky.
	 *
	 * @return the modified date of this lich su tai khoan dau ky
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lich su tai khoan dau ky.
	 *
	 * @param modifiedDate the modified date of this lich su tai khoan dau ky
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tai khoan doi ung ID of this lich su tai khoan dau ky.
	 *
	 * @return the tai khoan doi ung ID of this lich su tai khoan dau ky
	 */
	public long getTaiKhoanDoiUngId();

	/**
	 * Sets the tai khoan doi ung ID of this lich su tai khoan dau ky.
	 *
	 * @param taiKhoanDoiUngId the tai khoan doi ung ID of this lich su tai khoan dau ky
	 */
	public void setTaiKhoanDoiUngId(long taiKhoanDoiUngId);

	/**
	 * Returns the thang of this lich su tai khoan dau ky.
	 *
	 * @return the thang of this lich su tai khoan dau ky
	 */
	public int getThang();

	/**
	 * Sets the thang of this lich su tai khoan dau ky.
	 *
	 * @param thang the thang of this lich su tai khoan dau ky
	 */
	public void setThang(int thang);

	/**
	 * Returns the nam of this lich su tai khoan dau ky.
	 *
	 * @return the nam of this lich su tai khoan dau ky
	 */
	public int getNam();

	/**
	 * Sets the nam of this lich su tai khoan dau ky.
	 *
	 * @param nam the nam of this lich su tai khoan dau ky
	 */
	public void setNam(int nam);

	/**
	 * Returns the so tien ton of this lich su tai khoan dau ky.
	 *
	 * @return the so tien ton of this lich su tai khoan dau ky
	 */
	public Double getSoTienTon();

	/**
	 * Sets the so tien ton of this lich su tai khoan dau ky.
	 *
	 * @param soTienTon the so tien ton of this lich su tai khoan dau ky
	 */
	public void setSoTienTon(Double soTienTon);

	/**
	 * Returns the so tien thu of this lich su tai khoan dau ky.
	 *
	 * @return the so tien thu of this lich su tai khoan dau ky
	 */
	public Double getSoTienThu();

	/**
	 * Sets the so tien thu of this lich su tai khoan dau ky.
	 *
	 * @param soTienThu the so tien thu of this lich su tai khoan dau ky
	 */
	public void setSoTienThu(Double soTienThu);

	/**
	 * Returns the so tien chi of this lich su tai khoan dau ky.
	 *
	 * @return the so tien chi of this lich su tai khoan dau ky
	 */
	public Double getSoTienChi();

	/**
	 * Sets the so tien chi of this lich su tai khoan dau ky.
	 *
	 * @param soTienChi the so tien chi of this lich su tai khoan dau ky
	 */
	public void setSoTienChi(Double soTienChi);

	/**
	 * Returns the hoat dong of this lich su tai khoan dau ky.
	 *
	 * @return the hoat dong of this lich su tai khoan dau ky
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this lich su tai khoan dau ky.
	 *
	 * @param hoatDong the hoat dong of this lich su tai khoan dau ky
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LichSuTaiKhoanDauKy lichSuTaiKhoanDauKy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LichSuTaiKhoanDauKy> toCacheModel();

	@Override
	public LichSuTaiKhoanDauKy toEscapedModel();

	@Override
	public LichSuTaiKhoanDauKy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}