/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LichSuThuPhatChi service. Represents a row in the &quot;mb_lichsuthuphatchi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.LichSuThuPhatChiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.LichSuThuPhatChiImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LichSuThuPhatChi
 * @generated
 */
@ProviderType
public interface LichSuThuPhatChiModel
	extends BaseModel<LichSuThuPhatChi>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lich su thu phat chi model instance should use the {@link LichSuThuPhatChi} interface instead.
	 */

	/**
	 * Returns the primary key of this lich su thu phat chi.
	 *
	 * @return the primary key of this lich su thu phat chi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lich su thu phat chi.
	 *
	 * @param primaryKey the primary key of this lich su thu phat chi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lich su thu phat chi ID of this lich su thu phat chi.
	 *
	 * @return the lich su thu phat chi ID of this lich su thu phat chi
	 */
	public long getLichSuThuPhatChiId();

	/**
	 * Sets the lich su thu phat chi ID of this lich su thu phat chi.
	 *
	 * @param lichSuThuPhatChiId the lich su thu phat chi ID of this lich su thu phat chi
	 */
	public void setLichSuThuPhatChiId(long lichSuThuPhatChiId);

	/**
	 * Returns the company ID of this lich su thu phat chi.
	 *
	 * @return the company ID of this lich su thu phat chi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lich su thu phat chi.
	 *
	 * @param companyId the company ID of this lich su thu phat chi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this lich su thu phat chi.
	 *
	 * @return the group ID of this lich su thu phat chi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lich su thu phat chi.
	 *
	 * @param groupId the group ID of this lich su thu phat chi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this lich su thu phat chi.
	 *
	 * @return the user ID of this lich su thu phat chi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lich su thu phat chi.
	 *
	 * @param userId the user ID of this lich su thu phat chi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lich su thu phat chi.
	 *
	 * @return the user uuid of this lich su thu phat chi
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lich su thu phat chi.
	 *
	 * @param userUuid the user uuid of this lich su thu phat chi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lich su thu phat chi.
	 *
	 * @return the user name of this lich su thu phat chi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lich su thu phat chi.
	 *
	 * @param userName the user name of this lich su thu phat chi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lich su thu phat chi.
	 *
	 * @return the create date of this lich su thu phat chi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lich su thu phat chi.
	 *
	 * @param createDate the create date of this lich su thu phat chi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lich su thu phat chi.
	 *
	 * @return the modified date of this lich su thu phat chi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lich su thu phat chi.
	 *
	 * @param modifiedDate the modified date of this lich su thu phat chi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the phat vay ID of this lich su thu phat chi.
	 *
	 * @return the phat vay ID of this lich su thu phat chi
	 */
	public long getPhatVayId();

	/**
	 * Sets the phat vay ID of this lich su thu phat chi.
	 *
	 * @param phatVayId the phat vay ID of this lich su thu phat chi
	 */
	public void setPhatVayId(long phatVayId);

	/**
	 * Returns the ma ctv of this lich su thu phat chi.
	 *
	 * @return the ma ctv of this lich su thu phat chi
	 */
	@AutoEscape
	public String getMaCTV();

	/**
	 * Sets the ma ctv of this lich su thu phat chi.
	 *
	 * @param maCTV the ma ctv of this lich su thu phat chi
	 */
	public void setMaCTV(String maCTV);

	/**
	 * Returns the so tien of this lich su thu phat chi.
	 *
	 * @return the so tien of this lich su thu phat chi
	 */
	public Double getSoTien();

	/**
	 * Sets the so tien of this lich su thu phat chi.
	 *
	 * @param soTien the so tien of this lich su thu phat chi
	 */
	public void setSoTien(Double soTien);

	/**
	 * Returns the tong so tien von tra of this lich su thu phat chi.
	 *
	 * @return the tong so tien von tra of this lich su thu phat chi
	 */
	public Double getTongSoTienVonTra();

	/**
	 * Sets the tong so tien von tra of this lich su thu phat chi.
	 *
	 * @param tongSoTienVonTra the tong so tien von tra of this lich su thu phat chi
	 */
	public void setTongSoTienVonTra(Double tongSoTienVonTra);

	/**
	 * Returns the tong so tien lai tra of this lich su thu phat chi.
	 *
	 * @return the tong so tien lai tra of this lich su thu phat chi
	 */
	public Double getTongSoTienLaiTra();

	/**
	 * Sets the tong so tien lai tra of this lich su thu phat chi.
	 *
	 * @param tongSoTienLaiTra the tong so tien lai tra of this lich su thu phat chi
	 */
	public void setTongSoTienLaiTra(Double tongSoTienLaiTra);

	/**
	 * Returns the loai of this lich su thu phat chi.
	 *
	 * @return the loai of this lich su thu phat chi
	 */
	public int getLoai();

	/**
	 * Sets the loai of this lich su thu phat chi.
	 *
	 * @param loai the loai of this lich su thu phat chi
	 */
	public void setLoai(int loai);

	/**
	 * Returns the trang thai phat vay hien tai of this lich su thu phat chi.
	 *
	 * @return the trang thai phat vay hien tai of this lich su thu phat chi
	 */
	public int getTrangThaiPhatVayHienTai();

	/**
	 * Sets the trang thai phat vay hien tai of this lich su thu phat chi.
	 *
	 * @param trangThaiPhatVayHienTai the trang thai phat vay hien tai of this lich su thu phat chi
	 */
	public void setTrangThaiPhatVayHienTai(int trangThaiPhatVayHienTai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LichSuThuPhatChi lichSuThuPhatChi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LichSuThuPhatChi> toCacheModel();

	@Override
	public LichSuThuPhatChi toEscapedModel();

	@Override
	public LichSuThuPhatChi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}