/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LoaiTaiSan service. Represents a row in the &quot;dm_loaiTaiSan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.LoaiTaiSanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.LoaiTaiSanImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LoaiTaiSan
 * @generated
 */
@ProviderType
public interface LoaiTaiSanModel
	extends BaseModel<LoaiTaiSan>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loai tai san model instance should use the {@link LoaiTaiSan} interface instead.
	 */

	/**
	 * Returns the primary key of this loai tai san.
	 *
	 * @return the primary key of this loai tai san
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loai tai san.
	 *
	 * @param primaryKey the primary key of this loai tai san
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loai tai san ID of this loai tai san.
	 *
	 * @return the loai tai san ID of this loai tai san
	 */
	public long getLoaiTaiSanId();

	/**
	 * Sets the loai tai san ID of this loai tai san.
	 *
	 * @param loaiTaiSanId the loai tai san ID of this loai tai san
	 */
	public void setLoaiTaiSanId(long loaiTaiSanId);

	/**
	 * Returns the company ID of this loai tai san.
	 *
	 * @return the company ID of this loai tai san
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loai tai san.
	 *
	 * @param companyId the company ID of this loai tai san
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this loai tai san.
	 *
	 * @return the group ID of this loai tai san
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this loai tai san.
	 *
	 * @param groupId the group ID of this loai tai san
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this loai tai san.
	 *
	 * @return the user ID of this loai tai san
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loai tai san.
	 *
	 * @param userId the user ID of this loai tai san
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loai tai san.
	 *
	 * @return the user uuid of this loai tai san
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this loai tai san.
	 *
	 * @param userUuid the user uuid of this loai tai san
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loai tai san.
	 *
	 * @return the user name of this loai tai san
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loai tai san.
	 *
	 * @param userName the user name of this loai tai san
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loai tai san.
	 *
	 * @return the create date of this loai tai san
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loai tai san.
	 *
	 * @param createDate the create date of this loai tai san
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loai tai san.
	 *
	 * @return the modified date of this loai tai san
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loai tai san.
	 *
	 * @param modifiedDate the modified date of this loai tai san
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ten of this loai tai san.
	 *
	 * @return the ten of this loai tai san
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this loai tai san.
	 *
	 * @param ten the ten of this loai tai san
	 */
	public void setTen(String ten);

	/**
	 * Returns the ma of this loai tai san.
	 *
	 * @return the ma of this loai tai san
	 */
	@AutoEscape
	public String getMa();

	/**
	 * Sets the ma of this loai tai san.
	 *
	 * @param ma the ma of this loai tai san
	 */
	public void setMa(String ma);

	/**
	 * Returns the ghi chu of this loai tai san.
	 *
	 * @return the ghi chu of this loai tai san
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this loai tai san.
	 *
	 * @param ghiChu the ghi chu of this loai tai san
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the hoat dong of this loai tai san.
	 *
	 * @return the hoat dong of this loai tai san
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this loai tai san.
	 *
	 * @param hoatDong the hoat dong of this loai tai san
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LoaiTaiSan loaiTaiSan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LoaiTaiSan> toCacheModel();

	@Override
	public LoaiTaiSan toEscapedModel();

	@Override
	public LoaiTaiSan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}