/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Phieu service. Represents a row in the &quot;ketoan_phieu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.PhieuModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.PhieuImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Phieu
 * @generated
 */
@ProviderType
public interface PhieuModel
	extends BaseModel<Phieu>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phieu model instance should use the {@link Phieu} interface instead.
	 */

	/**
	 * Returns the primary key of this phieu.
	 *
	 * @return the primary key of this phieu
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phieu.
	 *
	 * @param primaryKey the primary key of this phieu
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the phieu ID of this phieu.
	 *
	 * @return the phieu ID of this phieu
	 */
	public long getPhieuId();

	/**
	 * Sets the phieu ID of this phieu.
	 *
	 * @param phieuId the phieu ID of this phieu
	 */
	public void setPhieuId(long phieuId);

	/**
	 * Returns the company ID of this phieu.
	 *
	 * @return the company ID of this phieu
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this phieu.
	 *
	 * @param companyId the company ID of this phieu
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this phieu.
	 *
	 * @return the group ID of this phieu
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this phieu.
	 *
	 * @param groupId the group ID of this phieu
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this phieu.
	 *
	 * @return the user ID of this phieu
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this phieu.
	 *
	 * @param userId the user ID of this phieu
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this phieu.
	 *
	 * @return the user uuid of this phieu
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this phieu.
	 *
	 * @param userUuid the user uuid of this phieu
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this phieu.
	 *
	 * @return the user name of this phieu
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this phieu.
	 *
	 * @param userName the user name of this phieu
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this phieu.
	 *
	 * @return the create date of this phieu
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this phieu.
	 *
	 * @param createDate the create date of this phieu
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this phieu.
	 *
	 * @return the modified date of this phieu
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this phieu.
	 *
	 * @param modifiedDate the modified date of this phieu
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ma ctv of this phieu.
	 *
	 * @return the ma ctv of this phieu
	 */
	@AutoEscape
	public String getMaCTV();

	/**
	 * Sets the ma ctv of this phieu.
	 *
	 * @param maCTV the ma ctv of this phieu
	 */
	public void setMaCTV(String maCTV);

	/**
	 * Returns the ho ten ctv of this phieu.
	 *
	 * @return the ho ten ctv of this phieu
	 */
	@AutoEscape
	public String getHoTenCTV();

	/**
	 * Sets the ho ten ctv of this phieu.
	 *
	 * @param hoTenCTV the ho ten ctv of this phieu
	 */
	public void setHoTenCTV(String hoTenCTV);

	/**
	 * Returns the so hop dong of this phieu.
	 *
	 * @return the so hop dong of this phieu
	 */
	@AutoEscape
	public String getSoHopDong();

	/**
	 * Sets the so hop dong of this phieu.
	 *
	 * @param soHopDong the so hop dong of this phieu
	 */
	public void setSoHopDong(String soHopDong);

	/**
	 * Returns the ngay chung tu of this phieu.
	 *
	 * @return the ngay chung tu of this phieu
	 */
	public Date getNgayChungTu();

	/**
	 * Sets the ngay chung tu of this phieu.
	 *
	 * @param ngayChungTu the ngay chung tu of this phieu
	 */
	public void setNgayChungTu(Date ngayChungTu);

	/**
	 * Returns the dia chi of this phieu.
	 *
	 * @return the dia chi of this phieu
	 */
	@AutoEscape
	public String getDiaChi();

	/**
	 * Sets the dia chi of this phieu.
	 *
	 * @param diaChi the dia chi of this phieu
	 */
	public void setDiaChi(String diaChi);

	/**
	 * Returns the so phieu of this phieu.
	 *
	 * @return the so phieu of this phieu
	 */
	@AutoEscape
	public String getSoPhieu();

	/**
	 * Sets the so phieu of this phieu.
	 *
	 * @param soPhieu the so phieu of this phieu
	 */
	public void setSoPhieu(String soPhieu);

	/**
	 * Returns the ngay ghi so of this phieu.
	 *
	 * @return the ngay ghi so of this phieu
	 */
	public Date getNgayGhiSo();

	/**
	 * Sets the ngay ghi so of this phieu.
	 *
	 * @param ngayGhiSo the ngay ghi so of this phieu
	 */
	public void setNgayGhiSo(Date ngayGhiSo);

	/**
	 * Returns the ma ms thu chi of this phieu.
	 *
	 * @return the ma ms thu chi of this phieu
	 */
	@AutoEscape
	public String getMaMSThuChi();

	/**
	 * Sets the ma ms thu chi of this phieu.
	 *
	 * @param maMSThuChi the ma ms thu chi of this phieu
	 */
	public void setMaMSThuChi(String maMSThuChi);

	/**
	 * Returns the so tien of this phieu.
	 *
	 * @return the so tien of this phieu
	 */
	public Double getSoTien();

	/**
	 * Sets the so tien of this phieu.
	 *
	 * @param soTien the so tien of this phieu
	 */
	public void setSoTien(Double soTien);

	/**
	 * Returns the chung tu kem theo of this phieu.
	 *
	 * @return the chung tu kem theo of this phieu
	 */
	@AutoEscape
	public String getChungTuKemTheo();

	/**
	 * Sets the chung tu kem theo of this phieu.
	 *
	 * @param chungTuKemTheo the chung tu kem theo of this phieu
	 */
	public void setChungTuKemTheo(String chungTuKemTheo);

	/**
	 * Returns the loai of this phieu.
	 *
	 * @return the loai of this phieu
	 */
	public int getLoai();

	/**
	 * Sets the loai of this phieu.
	 *
	 * @param loai the loai of this phieu
	 */
	public void setLoai(int loai);

	/**
	 * Returns the hoat dong of this phieu.
	 *
	 * @return the hoat dong of this phieu
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this phieu.
	 *
	 * @param hoatDong the hoat dong of this phieu
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Phieu phieu);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Phieu> toCacheModel();

	@Override
	public Phieu toEscapedModel();

	@Override
	public Phieu toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}