/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the QuanLyMaSo service. Represents a row in the &quot;dm_quanlymaso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.QuanLyMaSoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.QuanLyMaSoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QuanLyMaSo
 * @generated
 */
@ProviderType
public interface QuanLyMaSoModel extends BaseModel<QuanLyMaSo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a quan ly ma so model instance should use the {@link QuanLyMaSo} interface instead.
	 */

	/**
	 * Returns the primary key of this quan ly ma so.
	 *
	 * @return the primary key of this quan ly ma so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this quan ly ma so.
	 *
	 * @param primaryKey the primary key of this quan ly ma so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the quan ly ma so ID of this quan ly ma so.
	 *
	 * @return the quan ly ma so ID of this quan ly ma so
	 */
	public long getQuanLyMaSoId();

	/**
	 * Sets the quan ly ma so ID of this quan ly ma so.
	 *
	 * @param quanLyMaSoId the quan ly ma so ID of this quan ly ma so
	 */
	public void setQuanLyMaSoId(long quanLyMaSoId);

	/**
	 * Returns the key of this quan ly ma so.
	 *
	 * @return the key of this quan ly ma so
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this quan ly ma so.
	 *
	 * @param key the key of this quan ly ma so
	 */
	public void setKey(String key);

	/**
	 * Returns the so of this quan ly ma so.
	 *
	 * @return the so of this quan ly ma so
	 */
	public int getSo();

	/**
	 * Sets the so of this quan ly ma so.
	 *
	 * @param so the so of this quan ly ma so
	 */
	public void setSo(int so);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(QuanLyMaSo quanLyMaSo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<QuanLyMaSo> toCacheModel();

	@Override
	public QuanLyMaSo toEscapedModel();

	@Override
	public QuanLyMaSo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}