/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SoKheUoc service. Represents a row in the &quot;dm_sokheuoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.SoKheUocModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.SoKheUocImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SoKheUoc
 * @generated
 */
@ProviderType
public interface SoKheUocModel extends BaseModel<SoKheUoc> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a so khe uoc model instance should use the {@link SoKheUoc} interface instead.
	 */

	/**
	 * Returns the primary key of this so khe uoc.
	 *
	 * @return the primary key of this so khe uoc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this so khe uoc.
	 *
	 * @param primaryKey the primary key of this so khe uoc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the so khe uoc ID of this so khe uoc.
	 *
	 * @return the so khe uoc ID of this so khe uoc
	 */
	public long getSoKheUocId();

	/**
	 * Sets the so khe uoc ID of this so khe uoc.
	 *
	 * @param soKheUocId the so khe uoc ID of this so khe uoc
	 */
	public void setSoKheUocId(long soKheUocId);

	/**
	 * Returns the cau truc of this so khe uoc.
	 *
	 * @return the cau truc of this so khe uoc
	 */
	@AutoEscape
	public String getCauTruc();

	/**
	 * Sets the cau truc of this so khe uoc.
	 *
	 * @param cauTruc the cau truc of this so khe uoc
	 */
	public void setCauTruc(String cauTruc);

	/**
	 * Returns the so of this so khe uoc.
	 *
	 * @return the so of this so khe uoc
	 */
	public int getSo();

	/**
	 * Sets the so of this so khe uoc.
	 *
	 * @param so the so of this so khe uoc
	 */
	public void setSo(int so);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SoKheUoc soKheUoc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SoKheUoc> toCacheModel();

	@Override
	public SoKheUoc toEscapedModel();

	@Override
	public SoKheUoc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}