/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaiKhoanDoiUng service. Represents a row in the &quot;dm_taikhoandoiung&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.mb.model.impl.TaiKhoanDoiUngModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.mb.model.impl.TaiKhoanDoiUngImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaiKhoanDoiUng
 * @generated
 */
@ProviderType
public interface TaiKhoanDoiUngModel
	extends BaseModel<TaiKhoanDoiUng>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tai khoan doi ung model instance should use the {@link TaiKhoanDoiUng} interface instead.
	 */

	/**
	 * Returns the primary key of this tai khoan doi ung.
	 *
	 * @return the primary key of this tai khoan doi ung
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tai khoan doi ung.
	 *
	 * @param primaryKey the primary key of this tai khoan doi ung
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tai khoan doi ung ID of this tai khoan doi ung.
	 *
	 * @return the tai khoan doi ung ID of this tai khoan doi ung
	 */
	public long getTaiKhoanDoiUngId();

	/**
	 * Sets the tai khoan doi ung ID of this tai khoan doi ung.
	 *
	 * @param taiKhoanDoiUngId the tai khoan doi ung ID of this tai khoan doi ung
	 */
	public void setTaiKhoanDoiUngId(long taiKhoanDoiUngId);

	/**
	 * Returns the company ID of this tai khoan doi ung.
	 *
	 * @return the company ID of this tai khoan doi ung
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tai khoan doi ung.
	 *
	 * @param companyId the company ID of this tai khoan doi ung
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this tai khoan doi ung.
	 *
	 * @return the group ID of this tai khoan doi ung
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tai khoan doi ung.
	 *
	 * @param groupId the group ID of this tai khoan doi ung
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this tai khoan doi ung.
	 *
	 * @return the user ID of this tai khoan doi ung
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tai khoan doi ung.
	 *
	 * @param userId the user ID of this tai khoan doi ung
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tai khoan doi ung.
	 *
	 * @return the user uuid of this tai khoan doi ung
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tai khoan doi ung.
	 *
	 * @param userUuid the user uuid of this tai khoan doi ung
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tai khoan doi ung.
	 *
	 * @return the user name of this tai khoan doi ung
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tai khoan doi ung.
	 *
	 * @param userName the user name of this tai khoan doi ung
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tai khoan doi ung.
	 *
	 * @return the create date of this tai khoan doi ung
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tai khoan doi ung.
	 *
	 * @param createDate the create date of this tai khoan doi ung
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tai khoan doi ung.
	 *
	 * @return the modified date of this tai khoan doi ung
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tai khoan doi ung.
	 *
	 * @param modifiedDate the modified date of this tai khoan doi ung
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tai khoan doi ung cha ID of this tai khoan doi ung.
	 *
	 * @return the tai khoan doi ung cha ID of this tai khoan doi ung
	 */
	public long getTaiKhoanDoiUngChaId();

	/**
	 * Sets the tai khoan doi ung cha ID of this tai khoan doi ung.
	 *
	 * @param taiKhoanDoiUngChaId the tai khoan doi ung cha ID of this tai khoan doi ung
	 */
	public void setTaiKhoanDoiUngChaId(long taiKhoanDoiUngChaId);

	/**
	 * Returns the so hieu of this tai khoan doi ung.
	 *
	 * @return the so hieu of this tai khoan doi ung
	 */
	@AutoEscape
	public String getSoHieu();

	/**
	 * Sets the so hieu of this tai khoan doi ung.
	 *
	 * @param soHieu the so hieu of this tai khoan doi ung
	 */
	public void setSoHieu(String soHieu);

	/**
	 * Returns the ten of this tai khoan doi ung.
	 *
	 * @return the ten of this tai khoan doi ung
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this tai khoan doi ung.
	 *
	 * @param ten the ten of this tai khoan doi ung
	 */
	public void setTen(String ten);

	/**
	 * Returns the loai tai khoan of this tai khoan doi ung.
	 *
	 * @return the loai tai khoan of this tai khoan doi ung
	 */
	public int getLoaiTaiKhoan();

	/**
	 * Sets the loai tai khoan of this tai khoan doi ung.
	 *
	 * @param loaiTaiKhoan the loai tai khoan of this tai khoan doi ung
	 */
	public void setLoaiTaiKhoan(int loaiTaiKhoan);

	/**
	 * Returns the hoat dong of this tai khoan doi ung.
	 *
	 * @return the hoat dong of this tai khoan doi ung
	 */
	public Boolean getHoatDong();

	/**
	 * Sets the hoat dong of this tai khoan doi ung.
	 *
	 * @param hoatDong the hoat dong of this tai khoan doi ung
	 */
	public void setHoatDong(Boolean hoatDong);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaiKhoanDoiUng taiKhoanDoiUng);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaiKhoanDoiUng> toCacheModel();

	@Override
	public TaiKhoanDoiUng toEscapedModel();

	@Override
	public TaiKhoanDoiUng toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}