/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mb.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.mb.model.Phieu;
import com.mb.service.PhieuService;
import com.mb.service.persistence.CauHinhThuTienTruocFinder;
import com.mb.service.persistence.CauHinhThuTienTruocPersistence;
import com.mb.service.persistence.ChiNhanhFinder;
import com.mb.service.persistence.ChiNhanhPersistence;
import com.mb.service.persistence.CongTacVienFinder;
import com.mb.service.persistence.CongTacVienPersistence;
import com.mb.service.persistence.DsPhieuTaiKhoanFinder;
import com.mb.service.persistence.DsPhieuTaiKhoanPersistence;
import com.mb.service.persistence.KhachHangFinder;
import com.mb.service.persistence.KhachHangPersistence;
import com.mb.service.persistence.LaiSuatFinder;
import com.mb.service.persistence.LaiSuatPersistence;
import com.mb.service.persistence.LichSuTaiKhoanDauKyFinder;
import com.mb.service.persistence.LichSuTaiKhoanDauKyPersistence;
import com.mb.service.persistence.LichSuThuPhatChiFinder;
import com.mb.service.persistence.LichSuThuPhatChiPersistence;
import com.mb.service.persistence.LoaiTaiSanFinder;
import com.mb.service.persistence.LoaiTaiSanPersistence;
import com.mb.service.persistence.MaSoTheoDoiFinder;
import com.mb.service.persistence.MaSoTheoDoiPersistence;
import com.mb.service.persistence.MaSoThuChiFinder;
import com.mb.service.persistence.MaSoThuChiPersistence;
import com.mb.service.persistence.PhatVayFinder;
import com.mb.service.persistence.PhatVayPersistence;
import com.mb.service.persistence.PhieuFinder;
import com.mb.service.persistence.PhieuPersistence;
import com.mb.service.persistence.QuanLyMaSoPersistence;
import com.mb.service.persistence.SoKheUocFinder;
import com.mb.service.persistence.SoKheUocPersistence;
import com.mb.service.persistence.TaiKhoanDoiUngFinder;
import com.mb.service.persistence.TaiKhoanDoiUngPersistence;
import com.mb.service.persistence.TaiSanThueChapFinder;
import com.mb.service.persistence.TaiSanThueChapPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the phieu remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mb.service.impl.PhieuServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.mb.service.impl.PhieuServiceImpl
 * @generated
 */
public abstract class PhieuServiceBaseImpl
	extends BaseServiceImpl implements PhieuService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PhieuService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.mb.service.PhieuServiceUtil</code>.
	 */

	/**
	 * Returns the cau hinh thu tien truoc local service.
	 *
	 * @return the cau hinh thu tien truoc local service
	 */
	public com.mb.service.CauHinhThuTienTruocLocalService
		getCauHinhThuTienTruocLocalService() {

		return cauHinhThuTienTruocLocalService;
	}

	/**
	 * Sets the cau hinh thu tien truoc local service.
	 *
	 * @param cauHinhThuTienTruocLocalService the cau hinh thu tien truoc local service
	 */
	public void setCauHinhThuTienTruocLocalService(
		com.mb.service.CauHinhThuTienTruocLocalService
			cauHinhThuTienTruocLocalService) {

		this.cauHinhThuTienTruocLocalService = cauHinhThuTienTruocLocalService;
	}

	/**
	 * Returns the cau hinh thu tien truoc remote service.
	 *
	 * @return the cau hinh thu tien truoc remote service
	 */
	public com.mb.service.CauHinhThuTienTruocService
		getCauHinhThuTienTruocService() {

		return cauHinhThuTienTruocService;
	}

	/**
	 * Sets the cau hinh thu tien truoc remote service.
	 *
	 * @param cauHinhThuTienTruocService the cau hinh thu tien truoc remote service
	 */
	public void setCauHinhThuTienTruocService(
		com.mb.service.CauHinhThuTienTruocService cauHinhThuTienTruocService) {

		this.cauHinhThuTienTruocService = cauHinhThuTienTruocService;
	}

	/**
	 * Returns the cau hinh thu tien truoc persistence.
	 *
	 * @return the cau hinh thu tien truoc persistence
	 */
	public CauHinhThuTienTruocPersistence getCauHinhThuTienTruocPersistence() {
		return cauHinhThuTienTruocPersistence;
	}

	/**
	 * Sets the cau hinh thu tien truoc persistence.
	 *
	 * @param cauHinhThuTienTruocPersistence the cau hinh thu tien truoc persistence
	 */
	public void setCauHinhThuTienTruocPersistence(
		CauHinhThuTienTruocPersistence cauHinhThuTienTruocPersistence) {

		this.cauHinhThuTienTruocPersistence = cauHinhThuTienTruocPersistence;
	}

	/**
	 * Returns the cau hinh thu tien truoc finder.
	 *
	 * @return the cau hinh thu tien truoc finder
	 */
	public CauHinhThuTienTruocFinder getCauHinhThuTienTruocFinder() {
		return cauHinhThuTienTruocFinder;
	}

	/**
	 * Sets the cau hinh thu tien truoc finder.
	 *
	 * @param cauHinhThuTienTruocFinder the cau hinh thu tien truoc finder
	 */
	public void setCauHinhThuTienTruocFinder(
		CauHinhThuTienTruocFinder cauHinhThuTienTruocFinder) {

		this.cauHinhThuTienTruocFinder = cauHinhThuTienTruocFinder;
	}

	/**
	 * Returns the chi nhanh local service.
	 *
	 * @return the chi nhanh local service
	 */
	public com.mb.service.ChiNhanhLocalService getChiNhanhLocalService() {
		return chiNhanhLocalService;
	}

	/**
	 * Sets the chi nhanh local service.
	 *
	 * @param chiNhanhLocalService the chi nhanh local service
	 */
	public void setChiNhanhLocalService(
		com.mb.service.ChiNhanhLocalService chiNhanhLocalService) {

		this.chiNhanhLocalService = chiNhanhLocalService;
	}

	/**
	 * Returns the chi nhanh remote service.
	 *
	 * @return the chi nhanh remote service
	 */
	public com.mb.service.ChiNhanhService getChiNhanhService() {
		return chiNhanhService;
	}

	/**
	 * Sets the chi nhanh remote service.
	 *
	 * @param chiNhanhService the chi nhanh remote service
	 */
	public void setChiNhanhService(
		com.mb.service.ChiNhanhService chiNhanhService) {

		this.chiNhanhService = chiNhanhService;
	}

	/**
	 * Returns the chi nhanh persistence.
	 *
	 * @return the chi nhanh persistence
	 */
	public ChiNhanhPersistence getChiNhanhPersistence() {
		return chiNhanhPersistence;
	}

	/**
	 * Sets the chi nhanh persistence.
	 *
	 * @param chiNhanhPersistence the chi nhanh persistence
	 */
	public void setChiNhanhPersistence(
		ChiNhanhPersistence chiNhanhPersistence) {

		this.chiNhanhPersistence = chiNhanhPersistence;
	}

	/**
	 * Returns the chi nhanh finder.
	 *
	 * @return the chi nhanh finder
	 */
	public ChiNhanhFinder getChiNhanhFinder() {
		return chiNhanhFinder;
	}

	/**
	 * Sets the chi nhanh finder.
	 *
	 * @param chiNhanhFinder the chi nhanh finder
	 */
	public void setChiNhanhFinder(ChiNhanhFinder chiNhanhFinder) {
		this.chiNhanhFinder = chiNhanhFinder;
	}

	/**
	 * Returns the cong tac vien local service.
	 *
	 * @return the cong tac vien local service
	 */
	public com.mb.service.CongTacVienLocalService getCongTacVienLocalService() {
		return congTacVienLocalService;
	}

	/**
	 * Sets the cong tac vien local service.
	 *
	 * @param congTacVienLocalService the cong tac vien local service
	 */
	public void setCongTacVienLocalService(
		com.mb.service.CongTacVienLocalService congTacVienLocalService) {

		this.congTacVienLocalService = congTacVienLocalService;
	}

	/**
	 * Returns the cong tac vien remote service.
	 *
	 * @return the cong tac vien remote service
	 */
	public com.mb.service.CongTacVienService getCongTacVienService() {
		return congTacVienService;
	}

	/**
	 * Sets the cong tac vien remote service.
	 *
	 * @param congTacVienService the cong tac vien remote service
	 */
	public void setCongTacVienService(
		com.mb.service.CongTacVienService congTacVienService) {

		this.congTacVienService = congTacVienService;
	}

	/**
	 * Returns the cong tac vien persistence.
	 *
	 * @return the cong tac vien persistence
	 */
	public CongTacVienPersistence getCongTacVienPersistence() {
		return congTacVienPersistence;
	}

	/**
	 * Sets the cong tac vien persistence.
	 *
	 * @param congTacVienPersistence the cong tac vien persistence
	 */
	public void setCongTacVienPersistence(
		CongTacVienPersistence congTacVienPersistence) {

		this.congTacVienPersistence = congTacVienPersistence;
	}

	/**
	 * Returns the cong tac vien finder.
	 *
	 * @return the cong tac vien finder
	 */
	public CongTacVienFinder getCongTacVienFinder() {
		return congTacVienFinder;
	}

	/**
	 * Sets the cong tac vien finder.
	 *
	 * @param congTacVienFinder the cong tac vien finder
	 */
	public void setCongTacVienFinder(CongTacVienFinder congTacVienFinder) {
		this.congTacVienFinder = congTacVienFinder;
	}

	/**
	 * Returns the ds phieu tai khoan local service.
	 *
	 * @return the ds phieu tai khoan local service
	 */
	public com.mb.service.DsPhieuTaiKhoanLocalService
		getDsPhieuTaiKhoanLocalService() {

		return dsPhieuTaiKhoanLocalService;
	}

	/**
	 * Sets the ds phieu tai khoan local service.
	 *
	 * @param dsPhieuTaiKhoanLocalService the ds phieu tai khoan local service
	 */
	public void setDsPhieuTaiKhoanLocalService(
		com.mb.service.DsPhieuTaiKhoanLocalService
			dsPhieuTaiKhoanLocalService) {

		this.dsPhieuTaiKhoanLocalService = dsPhieuTaiKhoanLocalService;
	}

	/**
	 * Returns the ds phieu tai khoan remote service.
	 *
	 * @return the ds phieu tai khoan remote service
	 */
	public com.mb.service.DsPhieuTaiKhoanService getDsPhieuTaiKhoanService() {
		return dsPhieuTaiKhoanService;
	}

	/**
	 * Sets the ds phieu tai khoan remote service.
	 *
	 * @param dsPhieuTaiKhoanService the ds phieu tai khoan remote service
	 */
	public void setDsPhieuTaiKhoanService(
		com.mb.service.DsPhieuTaiKhoanService dsPhieuTaiKhoanService) {

		this.dsPhieuTaiKhoanService = dsPhieuTaiKhoanService;
	}

	/**
	 * Returns the ds phieu tai khoan persistence.
	 *
	 * @return the ds phieu tai khoan persistence
	 */
	public DsPhieuTaiKhoanPersistence getDsPhieuTaiKhoanPersistence() {
		return dsPhieuTaiKhoanPersistence;
	}

	/**
	 * Sets the ds phieu tai khoan persistence.
	 *
	 * @param dsPhieuTaiKhoanPersistence the ds phieu tai khoan persistence
	 */
	public void setDsPhieuTaiKhoanPersistence(
		DsPhieuTaiKhoanPersistence dsPhieuTaiKhoanPersistence) {

		this.dsPhieuTaiKhoanPersistence = dsPhieuTaiKhoanPersistence;
	}

	/**
	 * Returns the ds phieu tai khoan finder.
	 *
	 * @return the ds phieu tai khoan finder
	 */
	public DsPhieuTaiKhoanFinder getDsPhieuTaiKhoanFinder() {
		return dsPhieuTaiKhoanFinder;
	}

	/**
	 * Sets the ds phieu tai khoan finder.
	 *
	 * @param dsPhieuTaiKhoanFinder the ds phieu tai khoan finder
	 */
	public void setDsPhieuTaiKhoanFinder(
		DsPhieuTaiKhoanFinder dsPhieuTaiKhoanFinder) {

		this.dsPhieuTaiKhoanFinder = dsPhieuTaiKhoanFinder;
	}

	/**
	 * Returns the khach hang local service.
	 *
	 * @return the khach hang local service
	 */
	public com.mb.service.KhachHangLocalService getKhachHangLocalService() {
		return khachHangLocalService;
	}

	/**
	 * Sets the khach hang local service.
	 *
	 * @param khachHangLocalService the khach hang local service
	 */
	public void setKhachHangLocalService(
		com.mb.service.KhachHangLocalService khachHangLocalService) {

		this.khachHangLocalService = khachHangLocalService;
	}

	/**
	 * Returns the khach hang remote service.
	 *
	 * @return the khach hang remote service
	 */
	public com.mb.service.KhachHangService getKhachHangService() {
		return khachHangService;
	}

	/**
	 * Sets the khach hang remote service.
	 *
	 * @param khachHangService the khach hang remote service
	 */
	public void setKhachHangService(
		com.mb.service.KhachHangService khachHangService) {

		this.khachHangService = khachHangService;
	}

	/**
	 * Returns the khach hang persistence.
	 *
	 * @return the khach hang persistence
	 */
	public KhachHangPersistence getKhachHangPersistence() {
		return khachHangPersistence;
	}

	/**
	 * Sets the khach hang persistence.
	 *
	 * @param khachHangPersistence the khach hang persistence
	 */
	public void setKhachHangPersistence(
		KhachHangPersistence khachHangPersistence) {

		this.khachHangPersistence = khachHangPersistence;
	}

	/**
	 * Returns the khach hang finder.
	 *
	 * @return the khach hang finder
	 */
	public KhachHangFinder getKhachHangFinder() {
		return khachHangFinder;
	}

	/**
	 * Sets the khach hang finder.
	 *
	 * @param khachHangFinder the khach hang finder
	 */
	public void setKhachHangFinder(KhachHangFinder khachHangFinder) {
		this.khachHangFinder = khachHangFinder;
	}

	/**
	 * Returns the lai suat local service.
	 *
	 * @return the lai suat local service
	 */
	public com.mb.service.LaiSuatLocalService getLaiSuatLocalService() {
		return laiSuatLocalService;
	}

	/**
	 * Sets the lai suat local service.
	 *
	 * @param laiSuatLocalService the lai suat local service
	 */
	public void setLaiSuatLocalService(
		com.mb.service.LaiSuatLocalService laiSuatLocalService) {

		this.laiSuatLocalService = laiSuatLocalService;
	}

	/**
	 * Returns the lai suat remote service.
	 *
	 * @return the lai suat remote service
	 */
	public com.mb.service.LaiSuatService getLaiSuatService() {
		return laiSuatService;
	}

	/**
	 * Sets the lai suat remote service.
	 *
	 * @param laiSuatService the lai suat remote service
	 */
	public void setLaiSuatService(
		com.mb.service.LaiSuatService laiSuatService) {

		this.laiSuatService = laiSuatService;
	}

	/**
	 * Returns the lai suat persistence.
	 *
	 * @return the lai suat persistence
	 */
	public LaiSuatPersistence getLaiSuatPersistence() {
		return laiSuatPersistence;
	}

	/**
	 * Sets the lai suat persistence.
	 *
	 * @param laiSuatPersistence the lai suat persistence
	 */
	public void setLaiSuatPersistence(LaiSuatPersistence laiSuatPersistence) {
		this.laiSuatPersistence = laiSuatPersistence;
	}

	/**
	 * Returns the lai suat finder.
	 *
	 * @return the lai suat finder
	 */
	public LaiSuatFinder getLaiSuatFinder() {
		return laiSuatFinder;
	}

	/**
	 * Sets the lai suat finder.
	 *
	 * @param laiSuatFinder the lai suat finder
	 */
	public void setLaiSuatFinder(LaiSuatFinder laiSuatFinder) {
		this.laiSuatFinder = laiSuatFinder;
	}

	/**
	 * Returns the lich su tai khoan dau ky local service.
	 *
	 * @return the lich su tai khoan dau ky local service
	 */
	public com.mb.service.LichSuTaiKhoanDauKyLocalService
		getLichSuTaiKhoanDauKyLocalService() {

		return lichSuTaiKhoanDauKyLocalService;
	}

	/**
	 * Sets the lich su tai khoan dau ky local service.
	 *
	 * @param lichSuTaiKhoanDauKyLocalService the lich su tai khoan dau ky local service
	 */
	public void setLichSuTaiKhoanDauKyLocalService(
		com.mb.service.LichSuTaiKhoanDauKyLocalService
			lichSuTaiKhoanDauKyLocalService) {

		this.lichSuTaiKhoanDauKyLocalService = lichSuTaiKhoanDauKyLocalService;
	}

	/**
	 * Returns the lich su tai khoan dau ky remote service.
	 *
	 * @return the lich su tai khoan dau ky remote service
	 */
	public com.mb.service.LichSuTaiKhoanDauKyService
		getLichSuTaiKhoanDauKyService() {

		return lichSuTaiKhoanDauKyService;
	}

	/**
	 * Sets the lich su tai khoan dau ky remote service.
	 *
	 * @param lichSuTaiKhoanDauKyService the lich su tai khoan dau ky remote service
	 */
	public void setLichSuTaiKhoanDauKyService(
		com.mb.service.LichSuTaiKhoanDauKyService lichSuTaiKhoanDauKyService) {

		this.lichSuTaiKhoanDauKyService = lichSuTaiKhoanDauKyService;
	}

	/**
	 * Returns the lich su tai khoan dau ky persistence.
	 *
	 * @return the lich su tai khoan dau ky persistence
	 */
	public LichSuTaiKhoanDauKyPersistence getLichSuTaiKhoanDauKyPersistence() {
		return lichSuTaiKhoanDauKyPersistence;
	}

	/**
	 * Sets the lich su tai khoan dau ky persistence.
	 *
	 * @param lichSuTaiKhoanDauKyPersistence the lich su tai khoan dau ky persistence
	 */
	public void setLichSuTaiKhoanDauKyPersistence(
		LichSuTaiKhoanDauKyPersistence lichSuTaiKhoanDauKyPersistence) {

		this.lichSuTaiKhoanDauKyPersistence = lichSuTaiKhoanDauKyPersistence;
	}

	/**
	 * Returns the lich su tai khoan dau ky finder.
	 *
	 * @return the lich su tai khoan dau ky finder
	 */
	public LichSuTaiKhoanDauKyFinder getLichSuTaiKhoanDauKyFinder() {
		return lichSuTaiKhoanDauKyFinder;
	}

	/**
	 * Sets the lich su tai khoan dau ky finder.
	 *
	 * @param lichSuTaiKhoanDauKyFinder the lich su tai khoan dau ky finder
	 */
	public void setLichSuTaiKhoanDauKyFinder(
		LichSuTaiKhoanDauKyFinder lichSuTaiKhoanDauKyFinder) {

		this.lichSuTaiKhoanDauKyFinder = lichSuTaiKhoanDauKyFinder;
	}

	/**
	 * Returns the lich su thu phat chi local service.
	 *
	 * @return the lich su thu phat chi local service
	 */
	public com.mb.service.LichSuThuPhatChiLocalService
		getLichSuThuPhatChiLocalService() {

		return lichSuThuPhatChiLocalService;
	}

	/**
	 * Sets the lich su thu phat chi local service.
	 *
	 * @param lichSuThuPhatChiLocalService the lich su thu phat chi local service
	 */
	public void setLichSuThuPhatChiLocalService(
		com.mb.service.LichSuThuPhatChiLocalService
			lichSuThuPhatChiLocalService) {

		this.lichSuThuPhatChiLocalService = lichSuThuPhatChiLocalService;
	}

	/**
	 * Returns the lich su thu phat chi remote service.
	 *
	 * @return the lich su thu phat chi remote service
	 */
	public com.mb.service.LichSuThuPhatChiService getLichSuThuPhatChiService() {
		return lichSuThuPhatChiService;
	}

	/**
	 * Sets the lich su thu phat chi remote service.
	 *
	 * @param lichSuThuPhatChiService the lich su thu phat chi remote service
	 */
	public void setLichSuThuPhatChiService(
		com.mb.service.LichSuThuPhatChiService lichSuThuPhatChiService) {

		this.lichSuThuPhatChiService = lichSuThuPhatChiService;
	}

	/**
	 * Returns the lich su thu phat chi persistence.
	 *
	 * @return the lich su thu phat chi persistence
	 */
	public LichSuThuPhatChiPersistence getLichSuThuPhatChiPersistence() {
		return lichSuThuPhatChiPersistence;
	}

	/**
	 * Sets the lich su thu phat chi persistence.
	 *
	 * @param lichSuThuPhatChiPersistence the lich su thu phat chi persistence
	 */
	public void setLichSuThuPhatChiPersistence(
		LichSuThuPhatChiPersistence lichSuThuPhatChiPersistence) {

		this.lichSuThuPhatChiPersistence = lichSuThuPhatChiPersistence;
	}

	/**
	 * Returns the lich su thu phat chi finder.
	 *
	 * @return the lich su thu phat chi finder
	 */
	public LichSuThuPhatChiFinder getLichSuThuPhatChiFinder() {
		return lichSuThuPhatChiFinder;
	}

	/**
	 * Sets the lich su thu phat chi finder.
	 *
	 * @param lichSuThuPhatChiFinder the lich su thu phat chi finder
	 */
	public void setLichSuThuPhatChiFinder(
		LichSuThuPhatChiFinder lichSuThuPhatChiFinder) {

		this.lichSuThuPhatChiFinder = lichSuThuPhatChiFinder;
	}

	/**
	 * Returns the loai tai san local service.
	 *
	 * @return the loai tai san local service
	 */
	public com.mb.service.LoaiTaiSanLocalService getLoaiTaiSanLocalService() {
		return loaiTaiSanLocalService;
	}

	/**
	 * Sets the loai tai san local service.
	 *
	 * @param loaiTaiSanLocalService the loai tai san local service
	 */
	public void setLoaiTaiSanLocalService(
		com.mb.service.LoaiTaiSanLocalService loaiTaiSanLocalService) {

		this.loaiTaiSanLocalService = loaiTaiSanLocalService;
	}

	/**
	 * Returns the loai tai san remote service.
	 *
	 * @return the loai tai san remote service
	 */
	public com.mb.service.LoaiTaiSanService getLoaiTaiSanService() {
		return loaiTaiSanService;
	}

	/**
	 * Sets the loai tai san remote service.
	 *
	 * @param loaiTaiSanService the loai tai san remote service
	 */
	public void setLoaiTaiSanService(
		com.mb.service.LoaiTaiSanService loaiTaiSanService) {

		this.loaiTaiSanService = loaiTaiSanService;
	}

	/**
	 * Returns the loai tai san persistence.
	 *
	 * @return the loai tai san persistence
	 */
	public LoaiTaiSanPersistence getLoaiTaiSanPersistence() {
		return loaiTaiSanPersistence;
	}

	/**
	 * Sets the loai tai san persistence.
	 *
	 * @param loaiTaiSanPersistence the loai tai san persistence
	 */
	public void setLoaiTaiSanPersistence(
		LoaiTaiSanPersistence loaiTaiSanPersistence) {

		this.loaiTaiSanPersistence = loaiTaiSanPersistence;
	}

	/**
	 * Returns the loai tai san finder.
	 *
	 * @return the loai tai san finder
	 */
	public LoaiTaiSanFinder getLoaiTaiSanFinder() {
		return loaiTaiSanFinder;
	}

	/**
	 * Sets the loai tai san finder.
	 *
	 * @param loaiTaiSanFinder the loai tai san finder
	 */
	public void setLoaiTaiSanFinder(LoaiTaiSanFinder loaiTaiSanFinder) {
		this.loaiTaiSanFinder = loaiTaiSanFinder;
	}

	/**
	 * Returns the ma so theo doi local service.
	 *
	 * @return the ma so theo doi local service
	 */
	public com.mb.service.MaSoTheoDoiLocalService getMaSoTheoDoiLocalService() {
		return maSoTheoDoiLocalService;
	}

	/**
	 * Sets the ma so theo doi local service.
	 *
	 * @param maSoTheoDoiLocalService the ma so theo doi local service
	 */
	public void setMaSoTheoDoiLocalService(
		com.mb.service.MaSoTheoDoiLocalService maSoTheoDoiLocalService) {

		this.maSoTheoDoiLocalService = maSoTheoDoiLocalService;
	}

	/**
	 * Returns the ma so theo doi remote service.
	 *
	 * @return the ma so theo doi remote service
	 */
	public com.mb.service.MaSoTheoDoiService getMaSoTheoDoiService() {
		return maSoTheoDoiService;
	}

	/**
	 * Sets the ma so theo doi remote service.
	 *
	 * @param maSoTheoDoiService the ma so theo doi remote service
	 */
	public void setMaSoTheoDoiService(
		com.mb.service.MaSoTheoDoiService maSoTheoDoiService) {

		this.maSoTheoDoiService = maSoTheoDoiService;
	}

	/**
	 * Returns the ma so theo doi persistence.
	 *
	 * @return the ma so theo doi persistence
	 */
	public MaSoTheoDoiPersistence getMaSoTheoDoiPersistence() {
		return maSoTheoDoiPersistence;
	}

	/**
	 * Sets the ma so theo doi persistence.
	 *
	 * @param maSoTheoDoiPersistence the ma so theo doi persistence
	 */
	public void setMaSoTheoDoiPersistence(
		MaSoTheoDoiPersistence maSoTheoDoiPersistence) {

		this.maSoTheoDoiPersistence = maSoTheoDoiPersistence;
	}

	/**
	 * Returns the ma so theo doi finder.
	 *
	 * @return the ma so theo doi finder
	 */
	public MaSoTheoDoiFinder getMaSoTheoDoiFinder() {
		return maSoTheoDoiFinder;
	}

	/**
	 * Sets the ma so theo doi finder.
	 *
	 * @param maSoTheoDoiFinder the ma so theo doi finder
	 */
	public void setMaSoTheoDoiFinder(MaSoTheoDoiFinder maSoTheoDoiFinder) {
		this.maSoTheoDoiFinder = maSoTheoDoiFinder;
	}

	/**
	 * Returns the ma so thu chi local service.
	 *
	 * @return the ma so thu chi local service
	 */
	public com.mb.service.MaSoThuChiLocalService getMaSoThuChiLocalService() {
		return maSoThuChiLocalService;
	}

	/**
	 * Sets the ma so thu chi local service.
	 *
	 * @param maSoThuChiLocalService the ma so thu chi local service
	 */
	public void setMaSoThuChiLocalService(
		com.mb.service.MaSoThuChiLocalService maSoThuChiLocalService) {

		this.maSoThuChiLocalService = maSoThuChiLocalService;
	}

	/**
	 * Returns the ma so thu chi remote service.
	 *
	 * @return the ma so thu chi remote service
	 */
	public com.mb.service.MaSoThuChiService getMaSoThuChiService() {
		return maSoThuChiService;
	}

	/**
	 * Sets the ma so thu chi remote service.
	 *
	 * @param maSoThuChiService the ma so thu chi remote service
	 */
	public void setMaSoThuChiService(
		com.mb.service.MaSoThuChiService maSoThuChiService) {

		this.maSoThuChiService = maSoThuChiService;
	}

	/**
	 * Returns the ma so thu chi persistence.
	 *
	 * @return the ma so thu chi persistence
	 */
	public MaSoThuChiPersistence getMaSoThuChiPersistence() {
		return maSoThuChiPersistence;
	}

	/**
	 * Sets the ma so thu chi persistence.
	 *
	 * @param maSoThuChiPersistence the ma so thu chi persistence
	 */
	public void setMaSoThuChiPersistence(
		MaSoThuChiPersistence maSoThuChiPersistence) {

		this.maSoThuChiPersistence = maSoThuChiPersistence;
	}

	/**
	 * Returns the ma so thu chi finder.
	 *
	 * @return the ma so thu chi finder
	 */
	public MaSoThuChiFinder getMaSoThuChiFinder() {
		return maSoThuChiFinder;
	}

	/**
	 * Sets the ma so thu chi finder.
	 *
	 * @param maSoThuChiFinder the ma so thu chi finder
	 */
	public void setMaSoThuChiFinder(MaSoThuChiFinder maSoThuChiFinder) {
		this.maSoThuChiFinder = maSoThuChiFinder;
	}

	/**
	 * Returns the phat vay local service.
	 *
	 * @return the phat vay local service
	 */
	public com.mb.service.PhatVayLocalService getPhatVayLocalService() {
		return phatVayLocalService;
	}

	/**
	 * Sets the phat vay local service.
	 *
	 * @param phatVayLocalService the phat vay local service
	 */
	public void setPhatVayLocalService(
		com.mb.service.PhatVayLocalService phatVayLocalService) {

		this.phatVayLocalService = phatVayLocalService;
	}

	/**
	 * Returns the phat vay remote service.
	 *
	 * @return the phat vay remote service
	 */
	public com.mb.service.PhatVayService getPhatVayService() {
		return phatVayService;
	}

	/**
	 * Sets the phat vay remote service.
	 *
	 * @param phatVayService the phat vay remote service
	 */
	public void setPhatVayService(
		com.mb.service.PhatVayService phatVayService) {

		this.phatVayService = phatVayService;
	}

	/**
	 * Returns the phat vay persistence.
	 *
	 * @return the phat vay persistence
	 */
	public PhatVayPersistence getPhatVayPersistence() {
		return phatVayPersistence;
	}

	/**
	 * Sets the phat vay persistence.
	 *
	 * @param phatVayPersistence the phat vay persistence
	 */
	public void setPhatVayPersistence(PhatVayPersistence phatVayPersistence) {
		this.phatVayPersistence = phatVayPersistence;
	}

	/**
	 * Returns the phat vay finder.
	 *
	 * @return the phat vay finder
	 */
	public PhatVayFinder getPhatVayFinder() {
		return phatVayFinder;
	}

	/**
	 * Sets the phat vay finder.
	 *
	 * @param phatVayFinder the phat vay finder
	 */
	public void setPhatVayFinder(PhatVayFinder phatVayFinder) {
		this.phatVayFinder = phatVayFinder;
	}

	/**
	 * Returns the phieu local service.
	 *
	 * @return the phieu local service
	 */
	public com.mb.service.PhieuLocalService getPhieuLocalService() {
		return phieuLocalService;
	}

	/**
	 * Sets the phieu local service.
	 *
	 * @param phieuLocalService the phieu local service
	 */
	public void setPhieuLocalService(
		com.mb.service.PhieuLocalService phieuLocalService) {

		this.phieuLocalService = phieuLocalService;
	}

	/**
	 * Returns the phieu remote service.
	 *
	 * @return the phieu remote service
	 */
	public PhieuService getPhieuService() {
		return phieuService;
	}

	/**
	 * Sets the phieu remote service.
	 *
	 * @param phieuService the phieu remote service
	 */
	public void setPhieuService(PhieuService phieuService) {
		this.phieuService = phieuService;
	}

	/**
	 * Returns the phieu persistence.
	 *
	 * @return the phieu persistence
	 */
	public PhieuPersistence getPhieuPersistence() {
		return phieuPersistence;
	}

	/**
	 * Sets the phieu persistence.
	 *
	 * @param phieuPersistence the phieu persistence
	 */
	public void setPhieuPersistence(PhieuPersistence phieuPersistence) {
		this.phieuPersistence = phieuPersistence;
	}

	/**
	 * Returns the phieu finder.
	 *
	 * @return the phieu finder
	 */
	public PhieuFinder getPhieuFinder() {
		return phieuFinder;
	}

	/**
	 * Sets the phieu finder.
	 *
	 * @param phieuFinder the phieu finder
	 */
	public void setPhieuFinder(PhieuFinder phieuFinder) {
		this.phieuFinder = phieuFinder;
	}

	/**
	 * Returns the quan ly ma so local service.
	 *
	 * @return the quan ly ma so local service
	 */
	public com.mb.service.QuanLyMaSoLocalService getQuanLyMaSoLocalService() {
		return quanLyMaSoLocalService;
	}

	/**
	 * Sets the quan ly ma so local service.
	 *
	 * @param quanLyMaSoLocalService the quan ly ma so local service
	 */
	public void setQuanLyMaSoLocalService(
		com.mb.service.QuanLyMaSoLocalService quanLyMaSoLocalService) {

		this.quanLyMaSoLocalService = quanLyMaSoLocalService;
	}

	/**
	 * Returns the quan ly ma so remote service.
	 *
	 * @return the quan ly ma so remote service
	 */
	public com.mb.service.QuanLyMaSoService getQuanLyMaSoService() {
		return quanLyMaSoService;
	}

	/**
	 * Sets the quan ly ma so remote service.
	 *
	 * @param quanLyMaSoService the quan ly ma so remote service
	 */
	public void setQuanLyMaSoService(
		com.mb.service.QuanLyMaSoService quanLyMaSoService) {

		this.quanLyMaSoService = quanLyMaSoService;
	}

	/**
	 * Returns the quan ly ma so persistence.
	 *
	 * @return the quan ly ma so persistence
	 */
	public QuanLyMaSoPersistence getQuanLyMaSoPersistence() {
		return quanLyMaSoPersistence;
	}

	/**
	 * Sets the quan ly ma so persistence.
	 *
	 * @param quanLyMaSoPersistence the quan ly ma so persistence
	 */
	public void setQuanLyMaSoPersistence(
		QuanLyMaSoPersistence quanLyMaSoPersistence) {

		this.quanLyMaSoPersistence = quanLyMaSoPersistence;
	}

	/**
	 * Returns the so khe uoc local service.
	 *
	 * @return the so khe uoc local service
	 */
	public com.mb.service.SoKheUocLocalService getSoKheUocLocalService() {
		return soKheUocLocalService;
	}

	/**
	 * Sets the so khe uoc local service.
	 *
	 * @param soKheUocLocalService the so khe uoc local service
	 */
	public void setSoKheUocLocalService(
		com.mb.service.SoKheUocLocalService soKheUocLocalService) {

		this.soKheUocLocalService = soKheUocLocalService;
	}

	/**
	 * Returns the so khe uoc remote service.
	 *
	 * @return the so khe uoc remote service
	 */
	public com.mb.service.SoKheUocService getSoKheUocService() {
		return soKheUocService;
	}

	/**
	 * Sets the so khe uoc remote service.
	 *
	 * @param soKheUocService the so khe uoc remote service
	 */
	public void setSoKheUocService(
		com.mb.service.SoKheUocService soKheUocService) {

		this.soKheUocService = soKheUocService;
	}

	/**
	 * Returns the so khe uoc persistence.
	 *
	 * @return the so khe uoc persistence
	 */
	public SoKheUocPersistence getSoKheUocPersistence() {
		return soKheUocPersistence;
	}

	/**
	 * Sets the so khe uoc persistence.
	 *
	 * @param soKheUocPersistence the so khe uoc persistence
	 */
	public void setSoKheUocPersistence(
		SoKheUocPersistence soKheUocPersistence) {

		this.soKheUocPersistence = soKheUocPersistence;
	}

	/**
	 * Returns the so khe uoc finder.
	 *
	 * @return the so khe uoc finder
	 */
	public SoKheUocFinder getSoKheUocFinder() {
		return soKheUocFinder;
	}

	/**
	 * Sets the so khe uoc finder.
	 *
	 * @param soKheUocFinder the so khe uoc finder
	 */
	public void setSoKheUocFinder(SoKheUocFinder soKheUocFinder) {
		this.soKheUocFinder = soKheUocFinder;
	}

	/**
	 * Returns the tai khoan doi ung local service.
	 *
	 * @return the tai khoan doi ung local service
	 */
	public com.mb.service.TaiKhoanDoiUngLocalService
		getTaiKhoanDoiUngLocalService() {

		return taiKhoanDoiUngLocalService;
	}

	/**
	 * Sets the tai khoan doi ung local service.
	 *
	 * @param taiKhoanDoiUngLocalService the tai khoan doi ung local service
	 */
	public void setTaiKhoanDoiUngLocalService(
		com.mb.service.TaiKhoanDoiUngLocalService taiKhoanDoiUngLocalService) {

		this.taiKhoanDoiUngLocalService = taiKhoanDoiUngLocalService;
	}

	/**
	 * Returns the tai khoan doi ung remote service.
	 *
	 * @return the tai khoan doi ung remote service
	 */
	public com.mb.service.TaiKhoanDoiUngService getTaiKhoanDoiUngService() {
		return taiKhoanDoiUngService;
	}

	/**
	 * Sets the tai khoan doi ung remote service.
	 *
	 * @param taiKhoanDoiUngService the tai khoan doi ung remote service
	 */
	public void setTaiKhoanDoiUngService(
		com.mb.service.TaiKhoanDoiUngService taiKhoanDoiUngService) {

		this.taiKhoanDoiUngService = taiKhoanDoiUngService;
	}

	/**
	 * Returns the tai khoan doi ung persistence.
	 *
	 * @return the tai khoan doi ung persistence
	 */
	public TaiKhoanDoiUngPersistence getTaiKhoanDoiUngPersistence() {
		return taiKhoanDoiUngPersistence;
	}

	/**
	 * Sets the tai khoan doi ung persistence.
	 *
	 * @param taiKhoanDoiUngPersistence the tai khoan doi ung persistence
	 */
	public void setTaiKhoanDoiUngPersistence(
		TaiKhoanDoiUngPersistence taiKhoanDoiUngPersistence) {

		this.taiKhoanDoiUngPersistence = taiKhoanDoiUngPersistence;
	}

	/**
	 * Returns the tai khoan doi ung finder.
	 *
	 * @return the tai khoan doi ung finder
	 */
	public TaiKhoanDoiUngFinder getTaiKhoanDoiUngFinder() {
		return taiKhoanDoiUngFinder;
	}

	/**
	 * Sets the tai khoan doi ung finder.
	 *
	 * @param taiKhoanDoiUngFinder the tai khoan doi ung finder
	 */
	public void setTaiKhoanDoiUngFinder(
		TaiKhoanDoiUngFinder taiKhoanDoiUngFinder) {

		this.taiKhoanDoiUngFinder = taiKhoanDoiUngFinder;
	}

	/**
	 * Returns the tai san thue chap local service.
	 *
	 * @return the tai san thue chap local service
	 */
	public com.mb.service.TaiSanThueChapLocalService
		getTaiSanThueChapLocalService() {

		return taiSanThueChapLocalService;
	}

	/**
	 * Sets the tai san thue chap local service.
	 *
	 * @param taiSanThueChapLocalService the tai san thue chap local service
	 */
	public void setTaiSanThueChapLocalService(
		com.mb.service.TaiSanThueChapLocalService taiSanThueChapLocalService) {

		this.taiSanThueChapLocalService = taiSanThueChapLocalService;
	}

	/**
	 * Returns the tai san thue chap remote service.
	 *
	 * @return the tai san thue chap remote service
	 */
	public com.mb.service.TaiSanThueChapService getTaiSanThueChapService() {
		return taiSanThueChapService;
	}

	/**
	 * Sets the tai san thue chap remote service.
	 *
	 * @param taiSanThueChapService the tai san thue chap remote service
	 */
	public void setTaiSanThueChapService(
		com.mb.service.TaiSanThueChapService taiSanThueChapService) {

		this.taiSanThueChapService = taiSanThueChapService;
	}

	/**
	 * Returns the tai san thue chap persistence.
	 *
	 * @return the tai san thue chap persistence
	 */
	public TaiSanThueChapPersistence getTaiSanThueChapPersistence() {
		return taiSanThueChapPersistence;
	}

	/**
	 * Sets the tai san thue chap persistence.
	 *
	 * @param taiSanThueChapPersistence the tai san thue chap persistence
	 */
	public void setTaiSanThueChapPersistence(
		TaiSanThueChapPersistence taiSanThueChapPersistence) {

		this.taiSanThueChapPersistence = taiSanThueChapPersistence;
	}

	/**
	 * Returns the tai san thue chap finder.
	 *
	 * @return the tai san thue chap finder
	 */
	public TaiSanThueChapFinder getTaiSanThueChapFinder() {
		return taiSanThueChapFinder;
	}

	/**
	 * Sets the tai san thue chap finder.
	 *
	 * @param taiSanThueChapFinder the tai san thue chap finder
	 */
	public void setTaiSanThueChapFinder(
		TaiSanThueChapFinder taiSanThueChapFinder) {

		this.taiSanThueChapFinder = taiSanThueChapFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PhieuService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Phieu.class;
	}

	protected String getModelClassName() {
		return Phieu.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = phieuPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.mb.service.CauHinhThuTienTruocLocalService.class)
	protected com.mb.service.CauHinhThuTienTruocLocalService
		cauHinhThuTienTruocLocalService;

	@BeanReference(type = com.mb.service.CauHinhThuTienTruocService.class)
	protected com.mb.service.CauHinhThuTienTruocService
		cauHinhThuTienTruocService;

	@BeanReference(type = CauHinhThuTienTruocPersistence.class)
	protected CauHinhThuTienTruocPersistence cauHinhThuTienTruocPersistence;

	@BeanReference(type = CauHinhThuTienTruocFinder.class)
	protected CauHinhThuTienTruocFinder cauHinhThuTienTruocFinder;

	@BeanReference(type = com.mb.service.ChiNhanhLocalService.class)
	protected com.mb.service.ChiNhanhLocalService chiNhanhLocalService;

	@BeanReference(type = com.mb.service.ChiNhanhService.class)
	protected com.mb.service.ChiNhanhService chiNhanhService;

	@BeanReference(type = ChiNhanhPersistence.class)
	protected ChiNhanhPersistence chiNhanhPersistence;

	@BeanReference(type = ChiNhanhFinder.class)
	protected ChiNhanhFinder chiNhanhFinder;

	@BeanReference(type = com.mb.service.CongTacVienLocalService.class)
	protected com.mb.service.CongTacVienLocalService congTacVienLocalService;

	@BeanReference(type = com.mb.service.CongTacVienService.class)
	protected com.mb.service.CongTacVienService congTacVienService;

	@BeanReference(type = CongTacVienPersistence.class)
	protected CongTacVienPersistence congTacVienPersistence;

	@BeanReference(type = CongTacVienFinder.class)
	protected CongTacVienFinder congTacVienFinder;

	@BeanReference(type = com.mb.service.DsPhieuTaiKhoanLocalService.class)
	protected com.mb.service.DsPhieuTaiKhoanLocalService
		dsPhieuTaiKhoanLocalService;

	@BeanReference(type = com.mb.service.DsPhieuTaiKhoanService.class)
	protected com.mb.service.DsPhieuTaiKhoanService dsPhieuTaiKhoanService;

	@BeanReference(type = DsPhieuTaiKhoanPersistence.class)
	protected DsPhieuTaiKhoanPersistence dsPhieuTaiKhoanPersistence;

	@BeanReference(type = DsPhieuTaiKhoanFinder.class)
	protected DsPhieuTaiKhoanFinder dsPhieuTaiKhoanFinder;

	@BeanReference(type = com.mb.service.KhachHangLocalService.class)
	protected com.mb.service.KhachHangLocalService khachHangLocalService;

	@BeanReference(type = com.mb.service.KhachHangService.class)
	protected com.mb.service.KhachHangService khachHangService;

	@BeanReference(type = KhachHangPersistence.class)
	protected KhachHangPersistence khachHangPersistence;

	@BeanReference(type = KhachHangFinder.class)
	protected KhachHangFinder khachHangFinder;

	@BeanReference(type = com.mb.service.LaiSuatLocalService.class)
	protected com.mb.service.LaiSuatLocalService laiSuatLocalService;

	@BeanReference(type = com.mb.service.LaiSuatService.class)
	protected com.mb.service.LaiSuatService laiSuatService;

	@BeanReference(type = LaiSuatPersistence.class)
	protected LaiSuatPersistence laiSuatPersistence;

	@BeanReference(type = LaiSuatFinder.class)
	protected LaiSuatFinder laiSuatFinder;

	@BeanReference(type = com.mb.service.LichSuTaiKhoanDauKyLocalService.class)
	protected com.mb.service.LichSuTaiKhoanDauKyLocalService
		lichSuTaiKhoanDauKyLocalService;

	@BeanReference(type = com.mb.service.LichSuTaiKhoanDauKyService.class)
	protected com.mb.service.LichSuTaiKhoanDauKyService
		lichSuTaiKhoanDauKyService;

	@BeanReference(type = LichSuTaiKhoanDauKyPersistence.class)
	protected LichSuTaiKhoanDauKyPersistence lichSuTaiKhoanDauKyPersistence;

	@BeanReference(type = LichSuTaiKhoanDauKyFinder.class)
	protected LichSuTaiKhoanDauKyFinder lichSuTaiKhoanDauKyFinder;

	@BeanReference(type = com.mb.service.LichSuThuPhatChiLocalService.class)
	protected com.mb.service.LichSuThuPhatChiLocalService
		lichSuThuPhatChiLocalService;

	@BeanReference(type = com.mb.service.LichSuThuPhatChiService.class)
	protected com.mb.service.LichSuThuPhatChiService lichSuThuPhatChiService;

	@BeanReference(type = LichSuThuPhatChiPersistence.class)
	protected LichSuThuPhatChiPersistence lichSuThuPhatChiPersistence;

	@BeanReference(type = LichSuThuPhatChiFinder.class)
	protected LichSuThuPhatChiFinder lichSuThuPhatChiFinder;

	@BeanReference(type = com.mb.service.LoaiTaiSanLocalService.class)
	protected com.mb.service.LoaiTaiSanLocalService loaiTaiSanLocalService;

	@BeanReference(type = com.mb.service.LoaiTaiSanService.class)
	protected com.mb.service.LoaiTaiSanService loaiTaiSanService;

	@BeanReference(type = LoaiTaiSanPersistence.class)
	protected LoaiTaiSanPersistence loaiTaiSanPersistence;

	@BeanReference(type = LoaiTaiSanFinder.class)
	protected LoaiTaiSanFinder loaiTaiSanFinder;

	@BeanReference(type = com.mb.service.MaSoTheoDoiLocalService.class)
	protected com.mb.service.MaSoTheoDoiLocalService maSoTheoDoiLocalService;

	@BeanReference(type = com.mb.service.MaSoTheoDoiService.class)
	protected com.mb.service.MaSoTheoDoiService maSoTheoDoiService;

	@BeanReference(type = MaSoTheoDoiPersistence.class)
	protected MaSoTheoDoiPersistence maSoTheoDoiPersistence;

	@BeanReference(type = MaSoTheoDoiFinder.class)
	protected MaSoTheoDoiFinder maSoTheoDoiFinder;

	@BeanReference(type = com.mb.service.MaSoThuChiLocalService.class)
	protected com.mb.service.MaSoThuChiLocalService maSoThuChiLocalService;

	@BeanReference(type = com.mb.service.MaSoThuChiService.class)
	protected com.mb.service.MaSoThuChiService maSoThuChiService;

	@BeanReference(type = MaSoThuChiPersistence.class)
	protected MaSoThuChiPersistence maSoThuChiPersistence;

	@BeanReference(type = MaSoThuChiFinder.class)
	protected MaSoThuChiFinder maSoThuChiFinder;

	@BeanReference(type = com.mb.service.PhatVayLocalService.class)
	protected com.mb.service.PhatVayLocalService phatVayLocalService;

	@BeanReference(type = com.mb.service.PhatVayService.class)
	protected com.mb.service.PhatVayService phatVayService;

	@BeanReference(type = PhatVayPersistence.class)
	protected PhatVayPersistence phatVayPersistence;

	@BeanReference(type = PhatVayFinder.class)
	protected PhatVayFinder phatVayFinder;

	@BeanReference(type = com.mb.service.PhieuLocalService.class)
	protected com.mb.service.PhieuLocalService phieuLocalService;

	@BeanReference(type = PhieuService.class)
	protected PhieuService phieuService;

	@BeanReference(type = PhieuPersistence.class)
	protected PhieuPersistence phieuPersistence;

	@BeanReference(type = PhieuFinder.class)
	protected PhieuFinder phieuFinder;

	@BeanReference(type = com.mb.service.QuanLyMaSoLocalService.class)
	protected com.mb.service.QuanLyMaSoLocalService quanLyMaSoLocalService;

	@BeanReference(type = com.mb.service.QuanLyMaSoService.class)
	protected com.mb.service.QuanLyMaSoService quanLyMaSoService;

	@BeanReference(type = QuanLyMaSoPersistence.class)
	protected QuanLyMaSoPersistence quanLyMaSoPersistence;

	@BeanReference(type = com.mb.service.SoKheUocLocalService.class)
	protected com.mb.service.SoKheUocLocalService soKheUocLocalService;

	@BeanReference(type = com.mb.service.SoKheUocService.class)
	protected com.mb.service.SoKheUocService soKheUocService;

	@BeanReference(type = SoKheUocPersistence.class)
	protected SoKheUocPersistence soKheUocPersistence;

	@BeanReference(type = SoKheUocFinder.class)
	protected SoKheUocFinder soKheUocFinder;

	@BeanReference(type = com.mb.service.TaiKhoanDoiUngLocalService.class)
	protected com.mb.service.TaiKhoanDoiUngLocalService
		taiKhoanDoiUngLocalService;

	@BeanReference(type = com.mb.service.TaiKhoanDoiUngService.class)
	protected com.mb.service.TaiKhoanDoiUngService taiKhoanDoiUngService;

	@BeanReference(type = TaiKhoanDoiUngPersistence.class)
	protected TaiKhoanDoiUngPersistence taiKhoanDoiUngPersistence;

	@BeanReference(type = TaiKhoanDoiUngFinder.class)
	protected TaiKhoanDoiUngFinder taiKhoanDoiUngFinder;

	@BeanReference(type = com.mb.service.TaiSanThueChapLocalService.class)
	protected com.mb.service.TaiSanThueChapLocalService
		taiSanThueChapLocalService;

	@BeanReference(type = com.mb.service.TaiSanThueChapService.class)
	protected com.mb.service.TaiSanThueChapService taiSanThueChapService;

	@BeanReference(type = TaiSanThueChapPersistence.class)
	protected TaiSanThueChapPersistence taiSanThueChapPersistence;

	@BeanReference(type = TaiSanThueChapFinder.class)
	protected TaiSanThueChapFinder taiSanThueChapFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

}